### ISSUE TITLE
pwsh.exe not exiting on exception

### ISSUE THREAD

**Issue by njtpremier** [rabbitmq/rabbitmq-server#7038] opened 2023-01-25 20:57 UTC
https://github.com/rabbitmq/rabbitmq-server/blob/69781ffb639bf1a82139bface909b2ea1f4041ae/deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl#L148

Version installed: 3.11.5

Issue: I've noticed that pwsh.exe processes aren't being closed on my computer, and after a fresh reboot and 2 hours I have close to 50 pwsh.exe processes started from rabbit and the longer until reboot (or restart of rabbitmq service) the more I'll have. I looked into the log files and found that this component attempts to locate handle.exe (which I dont have installed) and then moves on to using powershell to retrieve the handle count for the rabbitmq service process. However, my logs are indicating that powershell call also fails: _2023-01-25 13:48:36.776000-06:00 [error] <0.509.0> Could not infer the number of file handles used: {badmatch,{error,timeout}}_

The above log comes from a catch block after calling the powershell command. 

Proposed Resolution: The issue of the orphaned powershell processes should be resolved by appending -ErrorAction Stop parameter to the powershel command. This way the error is returned to the caller and the powershell script is properly closed.

**Please append "-ErrorAction Stop" (without quotes) to the end of this powershell command.**

**Comment by lukebakken** [comment] 2023-01-25 21:25
Please provide the complete stack trace, if available. Ideally the entire RabbitMQ log file (attached, not pasted).

Do you have any idea _why_ that Powershell command could be taking longer than 5 seconds to execute in your environment?

**Comment by njtpremier** [comment] 2023-01-25 22:17
The sysinternals handle.exe is not on my system.

But no, I have no idea why it would take longer than 5 seconds... I've ran the command myself and its fairly quick to complete. Also, note that the issue doesn't occur every time. About once every 2 minutes (give or take) the pwsh.exe process doesn't exit/close.

I've attached a log from last time it was started. Hope that can shed some light on it. Also attached screenshot of the orphaned processes.

[rabbit@localhost.log](https://github.com/rabbitmq/rabbitmq-server/files/10504137/rabbit%40localhost.log)
![rabbit@localhost_2023-01-25](https://user-images.githubusercontent.com/39092375/214704287-545d30ab-6822-43f6-8024-60c725484589.png)

**Comment by lukebakken** [comment] 2023-01-25 23:03
Thanks that's helpful. Well, if you don't mind installing `handle.exe` to see if that resolves your issue I'd appreciate it! I'm getting a PR ready to address this issue.

**Comment by lukebakken** [comment] 2023-01-25 23:07
In addition, I don't think adding `-ErrorAction Stop` will fix this issue. The default error action is `Continue`, so the script should always exit.

What is more likely is that due to the 5 second timeout for the command in Erlang it's not stopping `pwsh.exe` process as it should.

**Comment by njtpremier** [comment] 2023-01-25 23:12
I will install handle.exe... however after some further testing it seems like I can reproduce it outside of Rabbit/Erlang in just a basic command prompt window -- if I run the command enough times. Here's the command I use: 
`"c:/Program Files/PowerShell/7/pwsh.exe" -NoLogo -NonInteractive -NoProfile -InputFormat Text -OutputFormat Text -Command "Get-Process -Id 58660 | Select-Object -ExpandProperty HandleCount"`

I've tried all these scenarios without any luck, all sourced from others online when searching for powershell hang or powershell not exiting command):
  adding -ErrorAction Stop parameter.
  adding -ExecutionPolicy Bypass parameter.
  adding -ExecutionPolicy Unrestricted parameter.
  appending < nul after last quote.

**Comment by lukebakken** [comment] 2023-01-25 23:22
Thanks, that's very interesting. So you're saying the command prints a number, but the shell never exits?

**Comment by lukebakken** [comment] 2023-01-25 23:24
What is the exact version and patch level of Windows you're using? What version of Powershell Core?

**Comment by njtpremier** [comment] 2023-01-25 23:30
Nope... it opens a hidden powershell process but in those cases the command prompt is hung. No output and no ability to cancel or move on. Either the powershell process needs to be killed or close command prompt.

I have 3 actually (cause Microsoft can't figure out how to play nicely with previous versions). The same major versions as another developer that this doesn't happen with. The powershell version it's using is 7.2.8.500. OS is 10.0.19044 Build 19044

Follow up... not sure where to install handle.exe to get it to work. Any pointers?

**Comment by lukebakken** [comment] 2023-01-25 23:32
> Follow up... not sure where to install handle.exe to get it to work. Any pointers?

I usually just extract the archive to C:\WINDOWS

**Comment by lukebakken** [comment] 2023-01-25 23:34
FWIW I'm using Powershell Core 7.3.1 and have yet to reproduce this issue by running the same command in `cmd.exe`:

```
C:\Users\bakkenl>"c:/Program Files/PowerShell/7/pwsh.exe" -NoLogo -NonInteractive -NoProfile -InputFormat Text -OutputFormat Text -Command "Get-Process -Id 21892 | Select-Object -ExpandProperty HandleCount"
387

C:\Users\bakkenl>"c:/Program Files/PowerShell/7/pwsh.exe" -NoLogo -NonInteractive -NoProfile -InputFormat Text -OutputFormat Text -Command "Get-Process -Id 21892 | Select-Object -ExpandProperty HandleCount"
387

C:\Users\bakkenl>"c:/Program Files/PowerShell/7/pwsh.exe" -NoLogo -NonInteractive -NoProfile -InputFormat Text -OutputFormat Text -Command "Get-Process -Id 21892 | Select-Object -ExpandProperty HandleCount"
387

C:\Users\bakkenl>"c:/Program Files/PowerShell/7/pwsh.exe" -NoLogo -NonInteractive -NoProfile -InputFormat Text -OutputFormat Text -Command "Get-Process -Id 21892 | Select-Object -ExpandProperty HandleCount"
387
```

**Comment by njtpremier** [comment] 2023-01-25 23:41
You know, that's the version my colleague has too, and he also doesn't have this issue I have... and then there's this article: https://www.reddit.com/r/PowerShell/comments/v6arrr/powershell_72x_almost_always_hangs_when_launched/ which make me think 7.2 is borked in some way.

Anyway, so far so good with Handle.exe... thanks for that.

If I get some free time soon, I might circle back around with testing powershell 7.3 on my PC. Thanks Luke.

**Comment by michaelklishin** [comment] 2023-01-26 00:35
Should this be moved to a discussion then? @lukebakken do we want to pursue the draft PR you have put together?

**Comment by lukebakken** [comment] 2023-01-26 15:50
The PR should address the issue of zombie processes being left behind in this case.

**Comment by lukebakken** [comment] 2023-01-26 17:11
Will be resolved by @njtpremier upgrading Powershell core, as well as #7039

**Closed by lukebakken** 2023-01-26 17:11 UTC

**Comment by njtpremier** [comment] 2023-01-26 17:42
Follow-up... while upgrading powershell to v7.3.1 did help reduce how often it happens, it didn't completely resolve the issue. I've since reverted back to using Handle.exe which has been working perfectly. The cause of powershell occasionally hanging on the command is unknown.

**Comment by lukebakken** [comment] 2023-01-26 18:59
Thanks for the update. When a release with #7039 is available I'll let you know. If you'd like to test that PR now, I can build a release with it for you. Let me know if you use the `.exe` installer or the `.zip` archive.
