### ISSUE TITLE
what time use Raft in rabbitmq? 

### ISSUE THREAD

**Issue by WithLin0510** [rabbitmq/rabbitmq-server#1569] opened 2018-04-02 08:07 UTC
![image](https://user-images.githubusercontent.com/22409551/38188561-1330eaea-368f-11e8-8787-6a68e5a1236f.png)

![image](https://user-images.githubusercontent.com/22409551/38188609-43d2b8ae-368f-11e8-9e16-38d9f0e884d1.png)

![image](https://user-images.githubusercontent.com/22409551/38188626-52999678-368f-11e8-9261-86ff519c4f6f.png)

What time use Raft in rabbitmq?

**Comment by michaelklishin** [comment] 2018-04-02 12:32
Duplicate of https://github.com/rabbitmq/ra/issues/15.

**Closed by michaelklishin** 2018-04-02 12:32 UTC
