### ISSUE TITLE
xenial Release Not Signed

### ISSUE THREAD

**Issue by kitplummer** [rabbitmq/rabbitmq-server#1996] opened 2019-04-30 13:31 UTC
Repository is missing Release.gpg.

```
Err:18 https://dl.bintray.com/rabbitmq/debian xenial Release.gpg
  404  Not Found
Get:19 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [747 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [684 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/rabbitmq/debian xenial Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by michaelklishin** [comment] 2019-04-30 13:41
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/1716.

**Closed by michaelklishin** 2019-04-30 13:41 UTC

**Comment by michaelklishin** [comment] 2019-04-30 13:47
Our team does not control how or when Bintray reindexes repositories. As of right now, there are traces of "work directories" in the [Bionic directory](https://dl.bintray.com/rabbitmq/debian/dists/bionic/), even though there were no recent GA releases (but alpha releases happen several times a day to a separate repository):

<img width="623" alt="Screenshot 2019-04-30 at 16 45 06" src="https://user-images.githubusercontent.com/1090/56966253-60b83800-6b67-11e9-99db-85c48ff45944.png">

We do not know why that's happening but some users contacted Bintray support and received an acknowledgement of "longer than expected reindexing operations". Our team provides a repository on [PackageCloud](https://packagecloud.io/rabbitmq/) for those who do not find Bintray a suitable option.

**Comment by michaelklishin** [comment] 2019-04-30 13:55
We have a theory as to what triggered reindexing this time. We [removed legacy Erlang packages](https://groups.google.com/forum/#!msg/rabbitmq-users/Gu55prdJ7uM/tftnTT_ZAwAJ) from Debian RPM repositories a few hours ago. This very likely required rebuidling of the entire repository — even though the `rabbitmq-server` package was not affected. This was a one time event as Erlang packages now [use a separate repository](https://bintray.com/rabbitmq-erlang).

That said, every time we produce a GA release the same reindexing process will be triggered again. We have no metrics or visibility into this from Bintray. Please contact JFrog to voice your concerns about this behaviour. Thank you.

**Comment by michaelklishin** [comment] 2019-04-30 17:16
We have republished 3.7.14 Debian package from Concourse to retrigger reindexing once again. It seems to be in progress but we have no visibility and cannot offer any kind of ETA :(

**Comment by michaelklishin** [comment] 2019-04-30 21:14
Reindexing seems to have finished:

```
curl https://dl.bintray.com/rabbitmq/debian/dists/bionic/Release.gpg
-----BEGIN PGP SIGNATURE-----
Version: BCPG v1.53

iQIcBAABCAAGBQJcyIZVAAoJEGtzo25gJt/KI4YP/iziULkPsl/F+Ti8ux4w54EK
SaLJiOAYpSSb/33UYuynzW9Cjl77iplW9e/q7sd0RIHKfPXDIHSBOHgBE29+bXe8
MVETSXpFWlWEvuxh02Zcqj3Y7GDC+icUTQT4UuakoJ1RPxdZl2B9CCHdAXRgYEBF
NQ/rbt8p1onxQ7yzwri0A4u2ORE7lwVPvtpPrt474yp87I6jlYsV/Ptg52H3uYuH
AsCTMEHA9+8XiXaWyrmnj25ZVvz3gz/z1UG1ZoIF0PoIlrJlHpgWufKioDnv8WQV
SWohATzZN6XULPvkpDPnVbkypJiA50KTUXZRUFHXBZBdOTOfvZsNoeGjIVZKLdSz
2TBVL89ET5qhTzubLqSSJztwIf5HXrkSxjeiNXgFro53De1YAD2C2Fw7K9TAVp1j
KwYlPd4GgqsE/4ADQoJANKvWSHOPYq1OUiQacOk2ldWL6/MJI5LZsainYd99O4T8
Xb3Y/LOwXxQj2DVZi4YKqhRnrdEaOf/g7GI4WG6YmkK50Yp3QUiMSB8VvxW+WE/2
HloV+cPm05xXaxB7fYCMe7j4rCOz9MsY5ixnhjAcoF6pz+cDexe9MV1ksd0IwWaz
DQ0hpf9rZ0r+a67UxoIMFg13xw8g/sNh3qQ7Gv+r7fAjy5SDdGk1Wr9VIUNf2rZO
fd+GKGFXLnIrMb020OOQ
=4s0+
-----END PGP SIGNATURE-----
```
