### ISSUE TITLE
Channel errors causing rabbit cluster to be unreachable

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#530] opened 2016-01-05 16:05 UTC
RabbitMQ cluster has been seen to exhibit some blocking behaviour, and becoming unreachable to external operations after being subjected to certain conditions. The logs reveal channel errors as below, which are caused by certain exchanges not being found. 

```
=ERROR REPORT==== 14-Dec-2015::16:44:40 ===
Channel error on connection <0.5462.0> (192.168.245.3:53044 -> 192.168.245.5:5672, vhost: '/', user: 'rmq_nova_user'), channel 1:
operation queue.bind caused a channel exception not_found: "no exchange 'reply_5f360ace6a4d4a9e83c9d276877e4d4b' in vhost '/'"
```
This also leads to some `channel_termination_timeout` exceptions as follows;

```
=CRASH REPORT==== 14-Dec-2015::16:49:05 ===
  crasher:
    initial call: rabbit_reader:init/4
    pid: <0.7418.0>
    registered_name: []
    exception exit: channel_termination_timeout
      in function  rabbit_reader:wait_for_channel_termination/3 (src/rabbit_reader.erl, line 766)
      in call from rabbit_reader:send_error_on_channel0_and_close/4 (src/rabbit_reader.erl, line 1503)
      in call from rabbit_reader:terminate/2 (src/rabbit_reader.erl, line 615)
      in call from rabbit_reader:handle_other/2 (src/rabbit_reader.erl, line 540)
      in call from rabbit_reader:mainloop/4 (src/rabbit_reader.erl, line 502)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 427)
      in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 385)
    ancestors: [<0.7416.0>,<0.2520.0>,<0.2519.0>,<0.2518.0>,rabbit_sup,
                  <0.634.0>]
    messages: [{'EXIT',#Port<0.22137>,normal}]
    links: []
    dictionary: [{{channel,1},
                   {<0.7445.0>,{method,rabbit_framing_amqp_0_9_1}}},
                  {process_name,
                      {rabbit_reader,
                          <<"192.168.245.8:48658 -> 192.168.245.3:5672">>}},
                  {{ch_pid,<0.7445.0>},{1,#Ref<0.0.0.40007>}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7946
  neighbours:
```

The following procedures can be carried out to reproduce this problem, assuming a Linux environment, Debian preferrably, RabbitMQ 3.4.3 or above, and preferrably Erlang 17.3;

On a 3 node cluster (`NODE_A`, `NODE_B`, `NODE_C`) with queue(s) decalred with HA policy set to `{"ha-mode": "all", "ha-sync-mode":"automatic"}` and `cluster_partition_handling` configured to `pause_minority`, apply traffic to the cluster whilst carrying out the following sequence of events, on `NODE_A` for example;

```
   rabbitmqctl list_channels
   rabbitmqctl stop_app
   rabbitmqctl reset
   rabbitmqctl join_cluster <rabbit@NODE_B>
   rabbitmqctl start_app
   rabbitmqctl list_queues -q synchronised_slave_pids
   sleep 2
   rabbitmq-server stop
   sleep 5
   service rabbitmq-server start
   iptables -A INPUT -s <NODE_B_IP> -p TCP -j DROP
   iptables -A INPUT -s <NODE_C_IP> -p TCP -j DROP
```

These procedures are repeated on `NODE_B` and `NODE_C`, with `NODE_B` joining `NODE_C`, and `NODE_C` joining `NODE_A`, respectively.

**Comment by michaelklishin** [comment] 2016-01-05 16:07
Can be relevant: https://github.com/rabbitmq/rabbitmq-server/issues/248.

**Comment by Ayanda-D** [comment] 2016-01-08 18:18
Similar to the feeedback given on [JIRA, VESC-574](https://issuetracker.springsource.com/browse/VESC-574), the same cause and blocking effects of this problem were reported in https://github.com/rabbitmq/rabbitmq-federation/issues/7, of which investigations have been carried out, and a patch been developed. The procedures and conditions mentioned above are reproducing and manifesting the same cluster blocking effect, however not based on the same channel error which was reported, i.e.

```
=ERROR REPORT==== 14-Dec-2015::16:44:40 ===
Channel error on connection <0.5462.0> (192.168.245.3:53044 -> 192.168.245.5:5672, vhost: '/', user: 'rmq_nova_user'), channel 1:
operation queue.bind caused a channel exception not_found: "no exchange 'reply_5f360ace6a4d4a9e83c9d276877e4d4b' in vhost '/'"
```

The patch which has been done directly addresses and fixes this problem; of channel errors caused by exchanges not being found in certain vhosts, which ultimately result in the rabbit cluster being unreachable. Shortly to follow is the progress of integrating this patch to [rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server) for the next scheduled release.

**Comment by michaelklishin** [comment] 2016-01-08 18:43
Thank you, @Ayanda-D and @dcorbacho. We will QA the issue before Monday noon and produce a build for the user to try.

**Comment by michaelklishin** [comment] 2016-01-11 11:35
We believe this is fixed in https://github.com/rabbitmq/rabbitmq-server/pull/533. Happy to provide a one-off build from `stable` to let interested folks help verify.

**Closed by michaelklishin** 2016-01-11 11:35 UTC

**Comment by Dixeat** [comment] 2016-01-28 10:09
Hi, we have the same problem in ubuntu on RabbitMQ V3.6.0-1.
Do you know, how can I fix it ?

**Comment by michaelklishin** [comment] 2016-01-28 10:10
@Dixeat wait for `3.6.1`.

**Comment by mageddo** [comment] 2016-07-14 15:28
Not solution for it?

**Comment by Ayanda-D** [comment] 2016-07-23 13:16
@mageddo this was fixed as of `3.6.1`. See #533 and #544.

**Comment by mageddo** [comment] 2016-07-24 02:43
Is funny because I had a problem like that but the cause was because the queues weren't created

**Comment by Ayanda-D** [comment] 2016-07-24 13:44
@mageddo thats interesting. If you have further questions concerning this, raise them on rabbitmq-users, along with all your logs. This will be dealt with separately, as we've moved on from this particular issue.

**NB:** RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions.

**Comment by Caberset** [comment] 2017-08-05 18:29
Just for be sure, take a look to your local network

# ip add

If there's no "lo" network, the you should enable it:

# ifconfig lo up

Then restart the server again and let's see if it works again now

# systemctl start rabbitmq-server
