### ISSUE TITLE
Error message is a list of ints when invalid file requested via HTTP GET

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2736] opened 2021-01-21 16:03 UTC
Reported in this `rabbitmq-users` thread:

https://groups.google.com/g/rabbitmq-users/c/P9sGVbCzGuo

I'm working on reproduction steps.

**Comment by deadtrickster** [comment] 2021-07-28 17:01
Can't reproduce. Closing.

**Closed by deadtrickster** 2021-07-28 17:01 UTC
Labels: rabbitmq-management, usability
