### ISSUE TITLE
High memory consumption with lazy queues in flow control

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#964] opened 2016-09-15 13:27 UTC
When the lazy queue gets in `flow` status, the msg_store seems not fast enough to save the messages, thus the messages are stored in memory.

 `reduce_memory_use` function should be the point to start.

```
reduce_memory_use(State = #vqstate {
                             mode = lazy,
                             ram_pending_ack  = RPA,
                             ram_msg_count    = RamMsgCount,
                             target_ram_count = TargetRamCount }) ->
    State1 = #vqstate { q3 = Q3 } =
        case chunk_size(RamMsgCount + gb_trees:size(RPA), TargetRamCount) of
            0  -> State;
            S1 -> {_, State2} =  limit_ram_acks(S1, State),
                  State2
        end,

    State3 =
        case chunk_size(?QUEUE:len(Q3),
                        permitted_beta_count(State1)) of
            0  ->
                State1;
            S2 -> push_betas_to_deltas(S2, State1) 
        end,
    garbage_collect(),
    State3.
```

**Comment by diaolanshan** [comment] 2016-09-30 13:21
We should wait for the next release for this or add a parameter can solve the issue?

**Comment by Gsantomaggio** [comment] 2016-09-30 14:00
@diaolanshan The new parameter `lazy_queue_explicit_gc_run_operation_threshold` will not solve this issue, but part of it.
Please see https://github.com/rabbitmq/rabbitmq-server/pull/978.

**Comment by Gsantomaggio** [comment] 2016-10-13 13:05
we looked in deep into the issue and just to clarify: 

The memory **does not grow up** always when the lazy queues get in flow status, but only under certain conditions. 

Here is two tests that explain in detail the problem:

**Test1 - 5 Connections - 10 Channels -  Body size 51200 bytes**
```
➜  scripts git:(rabbitmq-server-973) ✗ ./rabbitmqctl list_queues message_bytes message_bytes_ready message_bytes_ram name state policy
Listing queues ...
9145088000  9145088000  0 lazy.t_2  flow  Lazy
9145088000  9145088000  0 lazy.t_0  flow  Lazy
9145088000  9145088000  0 lazy.t_1  flow  Lazy
```
```
➜  scripts git:(rabbitmq-server-973) ✗ ./rabbitmqctl list_connections name state | grep -v running
Listing connections ...
127.0.0.1:61419 -> 127.0.0.1:5672 flow
127.0.0.1:61420 -> 127.0.0.1:5672 flow
127.0.0.1:61422 -> 127.0.0.1:5672 flow
127.0.0.1:61423 -> 127.0.0.1:5672 flow
127.0.0.1:61424 -> 127.0.0.1:5672 flow
```
```
➜  scripts git:(rabbitmq-server-973) ✗ ./rabbitmqctl list_channels name state | grep -v running
Listing channels ...
127.0.0.1:61419 -> 127.0.0.1:5672 (1) flow
127.0.0.1:61424 -> 127.0.0.1:5672 (2) flow
127.0.0.1:61423 -> 127.0.0.1:5672 (1) flow
127.0.0.1:61419 -> 127.0.0.1:5672 (2) flow
127.0.0.1:61422 -> 127.0.0.1:5672 (1) flow
127.0.0.1:61424 -> 127.0.0.1:5672 (3) flow
127.0.0.1:61419 -> 127.0.0.1:5672 (3) flow
127.0.0.1:61422 -> 127.0.0.1:5672 (2) flow
127.0.0.1:61423 -> 127.0.0.1:5672 (2) flow
127.0.0.1:61420 -> 127.0.0.1:5672 (1) flow
```
It works correctly. Queues, Connections and Channels get in flow status


**Test2 - 1050 connections and 1050 channels -  Body size 51200 bytes**
```
➜  scripts git:(rabbitmq-server-973) ✗ ./rabbitmqctl list_queues message_bytes message_bytes_ready message_bytes_ram name state policy
Listing queues ...
162304000 75264000  0 lazy.t_2 flow  Lazy
349286400 180326400 0 lazy.t_2 flow  Lazy
```
```
➜  scripts git:(rabbitmq-server-973) ✗ ./rabbitmqctl list_connections name state | grep -v running
Listing connections ...
```
```
➜  scripts git:(rabbitmq-server-973) ✗ ./rabbitmqctl list_channels name state | grep -v running
Listing channels ...
```

Here the queues get in flow status but connections and channels **don''t.**

In this case, the channels continue to publish the messages always in the same rate. 

***How to solve this situation?***

There are a few configurations to tune.
**Server Side:**
 - reduce the `credit_flow_default_credit`  in this case the channels get in flow status first.
 - increase `msg_store_file_size_limit`  
 - in same situation, can be useful to disable `fhc_*_buffering`
	 ```
	  {fhc_read_buffering,false},
	{fhc_write_buffering,false},
	```
 - Increase the file descriptors (`ulimit -n`)
 - Staring from `3.6.6` also this [parameter](https://github.com/rabbitmq/rabbitmq-server/issues/973) can be tuned 
 - using a cluster configuration can certainly helps, but the queues should be distributed equally across the nodes, to distribute the writes.

**Client Side:**
- for big string buffers (typically string serialization as `XML` or `JSON`  ), can be useful compress the buffers before publish it and decompress it after dequeue.

**Comment by michaelklishin** [comment] 2017-02-07 13:54
This issue ended up being a kitchen sink of questions. I'm leaning towards closing it because there is no definition of "done" any more for this, in particular since some workloads run into consumers not having enough network bandwidth (which is shared with producers).

**Comment by michaelklishin** [comment] 2017-05-08 15:17
We have identified the root cause in a specific app that was struggling with this: it used some 10K channels with 2 queues. With this ratio internal flow control no longer works effectively.

It has close to nothing to do with lazy queues.

**Closed by michaelklishin** 2017-05-08 15:17 UTC
Labels: bug, effort-medium
