### ISSUE TITLE
Rabbitmq Crash: Reason for termination == function_clause

### ISSUE THREAD

**Issue by brycechesternewman** [rabbitmq/rabbitmq-server#665] opened 2016-03-02 00:06 UTC
Hello,
We are running in pause_minority mode with 3 node cluster. 

RabbitMQ version is 3.5.6 in Docker running on CoreOS stable (835.10.0).
```
root         1     0  0 Feb16 ?        00:00:00 /bin/sh -e /usr/lib/rabbitmq/bin/rabbitmq-server
rabbitmq    77     1  0 Feb16 ?        00:00:08 /usr/lib/erlang/erts-7.1/bin/epmd -daemon
root      1197     1 48 Feb16 ?        7-05:43:31 /usr/lib/erlang/erts-7.1/bin/beam.smp -W w -A 64 -P 1048576 -K true -B i -- -root /usr/lib/erlang -progname erl -- -home /root -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.6/sbin/../ebin -noshell -noinput -s rabbit boot -sname rabbit@172-16-1-11 -boot start_sasl -config /etc/rabbitmq/rabbitmq -kernel inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger tty -rabbit error_logger tty -rabbit sasl_error_logger tty -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.6/sbin/../plugins" -rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
```

We observed a network partition when this crash occurred. Is there any other additional details I can provide?
```
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: =CRASH REPORT==== 16-Feb-2016::00:53:11 ===
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: crasher:
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: initial call: gen:init_it/6
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: pid: <0.1230.0>
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: registered_name: []
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: exception exit: {function_clause,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{orddict,fetch,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{13,<0.1230.0>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{{17,<3002.21673.547>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {view_member,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {17,<3002.21673.547>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {1,<3003.25601.2036>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {1,<3003.25601.2036>}}}]],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{file,"orddict.erl"},{line,80}]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,check_neighbours,1,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,change_view,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,handle_cast,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gen_server2,handle_msg,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {proc_lib,wake_up,3,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{file,"proc_lib.erl"},{line,250}]}]}
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: in function  gen_server2:terminate/3
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ancestors: [<0.1229.0>,<0.1228.0>,rabbit_amqqueue_sup_sup,rabbit_sup,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <0.217.0>]
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: messages: []
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: links: [<0.1229.0>]
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: dictionary: [{random_seed,{6653,16815,5139}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {process_name,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,{resource,<<"dsa">>,queue,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <<"dsa-casperaudit-image-jpg-280x280">>}}}]
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: trap_exit: false
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: status: running
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: heap_size: 610
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: stack_size: 27
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: reductions: 4137020913
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: neighbours:
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: =ERROR REPORT==== 16-Feb-2016::00:53:11 ===
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ** Generic server <0.1229.0> terminating
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ** Last message in was {'EXIT',<0.1230.0>,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {function_clause,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{orddict,fetch,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{13,<0.1230.0>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{{17,<3002.21673.547>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {view_member,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {17,<3002.21673.547>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {1,<3003.25601.2036>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {1,<3003.25601.2036>}}}]],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{file,"orddict.erl"},{line,80}]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,check_neighbours,1,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,change_view,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,handle_cast,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gen_server2,handle_msg,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {proc_lib,wake_up,3,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{file,"proc_lib.erl"},{line,250}]}]}}
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ** When Server state == {state,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {amqqueue,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {resource,<<"dsa">>,queue,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <<"dsa-casperaudit-image-jpg-280x280">>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: true,false,none,[],<3003.25643.2036>,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [<3002.11566.5678>],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [<3002.11566.5678>],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ['rabbit@172-16-1-10','rabbit@172-16-1-11'],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{vhost,<<"dsa">>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {name,<<"HA">>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {pattern,<<"^(?!amq\\.).*">>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {'apply-to',<<"all">>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {definition,[{<<"ha-mode">>,<<"all">>}]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {priority,0}],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{<3002.12615.5678>,<3002.11566.5678>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {<3003.25601.2036>,<3003.25643.2036>}],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [],live},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <0.1230.0>,rabbit_priority_queue,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {passthrough,rabbit_variable_queue,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {vqstate,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,{[],[]}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,{[],[]}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {delta,undefined,0,undefined},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,{[],[]}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,{[],[]}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: 5352797,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {qistate,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11/queues/DJLXBMPYB3FSDCTQRI2U677MC",
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: undefined,0,32768,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: #Fun<rabbit_variable_queue.2.97911988>,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: #Fun<rabbit_variable_queue.3.28467489>,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [],[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{client_msstate,msg_store_persistent,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <<177,30,46,85,101,130,206,194,238,148,116,144,70,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: 133,62,151>>,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {state,311376,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11/msg_store_persistent"},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: rabbit_msg_store_ets_index,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11/msg_store_persistent",
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <0.604.0>,315473,307279,319570,323667,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {2000,500}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {client_msstate,msg_store_transient,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <<214,250,125,158,93,236,199,204,245,253,141,203,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: 179,120,179,92>>,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {state,290891,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11/msg_store_transient"},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: rabbit_msg_store_ets_index,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: "/var/lib/rabbitmq/mnesia/rabbit@172-16-1-11/msg_store_transient",
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: <0.598.0>,294988,286794,299085,303182,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {2000,500}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: true,0,4096,0,0,0,0,0,infinity,0,0,0,0,0,0,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {rates,0.0,0.0,0.0,0.0,{1455,494707,85527}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {0,nil},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: 0,0,0,0,2048}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: undefined,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {erlang,#Ref<0.0.2026373121.185879>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {state,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {dict,0,16,16,8,80,48,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: []}}},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: delegate},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: 0}
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ** Reason for termination ==
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: ** {function_clause,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{orddict,fetch,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{13,<0.1230.0>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{{17,<3002.21673.547>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {view_member,
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {17,<3002.21673.547>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {1,<3003.25601.2036>},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {1,<3003.25601.2036>}}}]],
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: [{file,"orddict.erl"},{line,80}]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,check_neighbours,1,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,change_view,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gm,handle_cast,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {gen_server2,handle_msg,2,[]},
Feb 16 00:53:11 sea-dsa-prod-rabbitmq-0.novalocal bash[21852]: {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}
```

**Comment by michaelklishin** [comment] 2016-03-02 00:08
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/368.

**Closed by michaelklishin** 2016-03-02 00:08 UTC
