### ISSUE TITLE
Aggregated `queue_messages_published_total` metric violates Prometheus expectations about counters

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2783] opened 2021-02-02 16:53 UTC
See #2781 for the background.

Some metrics, e.g. `queue_messages_published_total` are computed as a basic sum aggregation of samples from a local ETS table, e.g. `channel_queue_exchange_metrics`. When a channel is closed, its samples are removed from the table,
decreasing the sum. This violates an expectation for `counter` metrics in Prometheus: they can only increment or stay flat or reset to 0 but not decrease.

The issue is not present when per-object metrics are used: when a channel is closed, all of its **metrics** go away, which is what the user expects to happen.

This is a side-effect of our quick-and-dirty switch to aggregated metrics. We need to retain this historical total or delegate
to the Prometheus client library which will do most aggregation work and handle resets.

This is node local state, so we can address this even with a significant rework of the Prometheus plugin and still ship it in a `3.8.x` release.

Per discussion with @dcorbacho @gerhard @kjnilsson.

**Comment by gerhard** [comment] 2021-02-02 18:26
Will be picking this one up first thing, and working with @dcorbacho on the review so that she can continue focusing on her in-flight.

**Comment by dcorbacho** [comment] 2021-02-03 10:25
Luckily we're not tracking totals on the channel but doing increments, see https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/src/rabbit_channel.erl#L205

So when `queue_exchange_stats` are increased we can use that value to increase a *new* publish counter to track totals per node (or even exchange).  Here: https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/src/rabbit_channel.erl#L2123

**Comment by karanlik** [comment] 2021-07-07 09:10
Hi All, 

Please sorry if i'm posting at a wrong place. 

Currently we're seeing some behaviour similar to this issue; our "rabbitmq_channel_messages_published_total" metrics (with aggregation enabled) decreases which causes false alarms & mis-guiding graphs. I guess this is some sort of bug or at least something not good for Prometheus. What is the proposed workaround-solution for such kind of situation? Going to per-object metrics ? 
Once again sorry if I'm at wrong location.
Thanks...

**Comment by gerhard** [comment] 2021-07-07 10:07
The fix is already available in what will become 3.9.0: https://github.com/rabbitmq/rabbitmq-server/pull/3127

You will notice that the PR has 5 more outstanding tasks, the next one being a back-port to v3.8.x. Once this is done, the issue will be fixed via an update to the dashboard (also one of those 5 tasks).

Between [RabbitMQ Summit](https://rabbitmqsummit.com/) - will you be joining us for today's pre-conference meetup @karanlik? 😉 - and a few other things in flight (3.9.0 being the most significant one by far), this back-port is going slower than I would like. The important take-away is that it's coming and it definitely fixes the issue (we have been testing it for weeks in our 3.9 long-running environment).

Hope that helps 👍🏻

**Comment by karanlik** [comment] 2021-07-07 10:52
Great! Thanks for your quick feedback.. I'll give a try to per-object based metrics until this is available.. best regards..(PS: I've subscribed t o RabbitMQ Summit mailing list :-) )

**Comment by luos** [comment] 2021-11-03 08:00
Hi,

Do you think this will get backported to 3.8.x?

Thanks

**Comment by MirahImage** [comment] 2022-05-10 10:18
Closing. As this is available in 3.9 and 3.10, and 3.8 is in extended support.

**Closed by MirahImage** 2022-05-10 10:18 UTC
Labels: bug, usability, rabbitmq-prometheus

**Comment by Cookieees** [comment] 2025-05-23 15:34
I apologize if I'm also writing in the wrong place or missing something..... 

I am currently using 4.06 in k8s with RabbitMQ Operator, and I am experiencing the same problem. After reading the [related discussion](https://github.com/rabbitmq/rabbitmq-server/discussions/2781) and the posts in this issue I concluded that by 4.06 this has been fixed. 

However, I am still seeing ‘floating’ metrics ‘rabbitmq_channel_messages_published_total’ and ‘rabbitmq_queue_messages_published_total’ which are not ‘counter’ as stated in the documentation.

If the problem is solved by adding some other metrics - please point to the place in the documentation where they are described, because I seem to have dug through everything. 🙏 

![Image](https://github.com/user-attachments/assets/8045c97f-5a8c-49cb-9826-8e6bcfc48928)

**Comment by michaelklishin** [comment] 2025-05-24 01:06
@Cookieees RabbitMQ 4.0.x is [out of community support](https://www.rabbitmq.com/release-information).

The right place to ask questions is GitHub discussions and Discord, not issues from over three years ago.

There are two places where the available metrics are listed:

 * [In the Prometheus guide](https://www.rabbitmq.com/docs/prometheus#detailed-endpoint) (should be the source of truth now)
 * [In the Prometheus plugin directory](https://www.rabbitmq.com/docs/prometheus#detailed-endpoint) (the original location)
