### ISSUE TITLE
500 Error when sorting queues by column in RabbitMQ 4.0.2 management plugin

### ISSUE THREAD

**Issue by JuanJo-RC** [rabbitmq/rabbitmq-server#12529] opened 2024-10-16 15:11 UTC
### Describe the bug

In RabbitMQ 4.0.2 with the management plugin, when listing queues, everything works as expected. However, attempting to sort the queue list by any column (e.g., messages) results in a 500 Internal Server Error.

https://domain/api/queues?page=1&page_size=100&name=&use_regex=false&**sort=messages&sort_reverse=false**&pagination=true ->Error 500
https://domain/api/queues?page=1&page_size=100&name=&use_regex=false&pagination=true --> OK

### Reproduction steps

1-Access the RabbitMQ management interface.
2-Go to the queues page.
3-Attempt to sort the queues by the "messages" column or any other column.
4-The server returns a 500 Internal Server Error.

### Expected behavior

The queue list should be sorted by the selected column without returning an error.

**Comment by michaelklishin** [comment] 2024-10-16 17:50
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/12367.

**Closed by michaelklishin** 2024-10-16 17:50 UTC
Labels: duplicate
