### ISSUE TITLE
OAuth plugin setting additional_scopes_key doesn't work as documented

### ISSUE THREAD

**Issue by ngbrown** [rabbitmq/rabbitmq-server#4160] opened 2022-02-17 00:54 UTC
The `auth_oauth2.additional_scopes_key` is described in the readme as:

| Key                                      | Documentation     
|------------------------------------------|-----------
| `auth_oauth2.additional_scopes_key`      | Configure the plugin to also look in other fields (maps to `additional_rabbitmq_scopes` in the old format).

(at [Line 147](https://github.com/rabbitmq/rabbitmq-server/blob/bea9306ff99ad8cc13e3620121d24b35cdf0802b/deps/rabbitmq_auth_backend_oauth2/README.md?plain=1#L147))

The `additional_scopes_key` setting is even mapped to `additional_rabbitmq_scopes` in the schema file. The problem is, that `additional_rabbitmq_scopes` is never used in the plugin. `extra_scopes_source` is used and the documentation for the advanced configuration also uses `extra_scopes_source`.

Should I submit a pull request as described in these changes? https://github.com/rabbitmq/rabbitmq-server/compare/v3.9.13...ngbrown-forks:oauth2-extra-scope?expand=1

Or alternatively, if the schema is correct and the documentation for the advanced configuration is bad, then this one? https://github.com/rabbitmq/rabbitmq-server/compare/v3.9.13...ngbrown-forks:oauth2-extra-scope-alt?expand=1

Both alternatives have been tested to work with the `roles` field provided by an Azure Active Directory JWT access token.

**Comment by luos** [comment] 2022-02-17 10:32
Hi, I think this was fixed in https://github.com/rabbitmq/rabbitmq-server/pull/4103 recently. 

What do you think?

**Comment by michaelklishin** [comment] 2022-02-17 10:56
Duplicate of #4103.

**Closed by michaelklishin** 2022-02-17 10:56 UTC

**Comment by ngbrown** [comment] 2022-02-17 14:40
Sorry for not finding the duplicate issue.

I rebased my patch to `master` and noticed that the `README.md` wasn't updated and the values in the test suite were not updated either.

https://github.com/rabbitmq/rabbitmq-server/compare/bea9306f...ngbrown-forks:oauth2-extra-scope-master?expand=1

**Comment by luos** [comment] 2022-02-17 16:01
I don't think the test values need updating as they are the `configuration value` for `extra_scopes_source`. 

You are correct, the README.md and comments in the schema are incorrect.
