### ISSUE TITLE
SASL PLAIN authentication fails if client includes non zero length authzid

### ISSUE THREAD

**Issue by k-wall** [rabbitmq/rabbitmq-server#2586] opened 2020-05-10 08:12 UTC
I am trying to connect software that uses Apache Qpid Proton to RabbitMQ.  I wish to authenticate with user name and password.  I notice that the SASL PLAIN authentication fails if the initial-response includes a non-zero `authzid ` part.

Demonstrating the issue with Qpid Proton CPP example simple_connect (0.30.0) on Fedora release 31.

```
$ ./simple_connect -u guest -p guest -m PLAIN -i
[0x5d7b50]: SASL:FRAME:  -> SASL
[0x5d7b50]: SASL:FRAME:  <- SASL
[0x5d7b50]: AMQP:FRAME:0 <- @sasl-mechanisms(64) [sasl-server-mechanisms=@PN_SYMBOL[:ANONYMOUS, :PLAIN]]
[0x5d7b50]: AMQP:FRAME:0 -> @sasl-init(65) [mechanism=:PLAIN, initial-response=b"guest\x00guest\x00guest"]
[0x5d7b50]:   IO:FRAME:  -> EOS
proton:io: Connection reset by peer - disconnected 127.0.0.1:5672
```

On the RabbitMQ side, I see the following:

```
2020-05-10 09:04:18.778 [info] <0.2020.0> accepting AMQP connection <0.2020.0> (127.0.0.1:41106 -> 127.0.0.1:5672)
2020-05-10 09:04:21.814 [error] <0.2020.0> closing AMQP connection <0.2020.0> (127.0.0.1:41106 -> 127.0.0.1:5672):
{handshake_error,starting,0,{'v1_0.error',{symbol,<<"amqp:decode-error">>},{utf8,<<"response <<103,117,101,115,116,0,103,117,101,115,116,0,103,117,101,115,116>> invalid">>},undefined}}
```

I don't think RabbitMQ has the concept of one user assuming the identity of another, but if `authzid == authcid` (as is my case here), I think RabbitMQ ought to accept the authentication.  

If I try with a client that does not send the authzid part I see no problem.

**Comment by ansd** [comment] 2024-11-15 16:33
> but if authzid == authcid (as is my case here), I think RabbitMQ ought to accept the authentication.

I agree.

@k-wall @IDonut or anyone else reading this: If you can provide me step by step instructions on how to repro this issue with any AMQP 1.0 or AMQP 0.9.1 client, I can fix this issue on the RabbitMQ side.

@k-wall specifically it's unclear to me how to build and run https://github.com/apache/qpid-proton/blob/main/cpp/examples/simple_connect.cpp

**Comment by ansd** [comment] 2024-11-15 17:06
Ok, I figured out how to build and run this C++ example.
In the root directory of https://github.com/apache/qpid-proton (`main` branch):
```bash
~/workspace/qpid-proton$ mkdir build
~/workspace/qpid-proton$ cd build
~/workspace/qpid-proton/build$ cmake ..
~/workspace/qpid-proton/build$ make simple_connect
~/workspace/qpid-proton/build$ ./cpp/examples/simple_connect -u guest -p guest -m PLAIN -i
```

This example succeeds against RabbitMQ v4.0.3.
RabbitMQ logs the following:
```
2024-11-15 17:02:01.190258+00:00 [info] <0.1072.0> accepting AMQP connection 127.0.0.1:47792 -> 127.0.0.1:5672
2024-11-15 17:02:01.190491+00:00 [debug] <0.1072.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2024-11-15 17:02:01.190682+00:00 [info] <0.1072.0> Connection from AMQP 1.0 container 'fee1a0fd-fb18-467e-b6ec-308e298ee285': user 'guest' authenticated using SASL mechanism PLAIN and granted access to vhost '/'
2024-11-15 17:02:01.190781+00:00 [debug] <0.1072.0> AMQP 1.0 connection.open frame: hostname = 127.0.0.1, extracted vhost = /, idle-time-out = undefined
2024-11-15 17:02:01.191483+00:00 [info] <0.1072.0> closing AMQP connection (127.0.0.1:47792 -> 127.0.0.1:5672, duration: '1ms')
```

>  using AMQ Interconnect Router (customised Qpid Dispatch Router) to connect to RabbitMQ

@IDonut, please provide exact steps how to reproduce.

For now, I'm closing this issue since it's not reproducible. We can re-open if someone comes up with repro steps.

**Closed by ansd** 2024-11-15 17:06 UTC
Labels: rabbitmq-amqp1.0
