### ISSUE TITLE
Incorrect statistics for channels

### ISSUE THREAD

**Issue by dqminh** [rabbitmq/rabbitmq-server#712] opened 2016-03-29 14:27 UTC
Noticed our rabbitmq cluster reported incorrect statistics for number of channels today, but `rabbitmqctl list-channels` returned correct results.

```
# on the stats API this returns 77k channels
> rabbitmqctl list_channels | wc -l                                                                          
1685
```

Restarting the stats process via `rabbitmqctl eval 'exit(erlang:whereis(rabbit_mgmt_db), please_terminate).'` makes the stats API return correct results again.

**Comment by michaelklishin** [comment] 2016-03-29 14:30
Management database is eventually consistent and due to https://github.com/rabbitmq/rabbitmq-management/issues/41 can voluntarily drop events, which can lead to this. I'm closing this as a duplicate of https://github.com/rabbitmq/rabbitmq-management/issues/41, since that's the biggest contributing factor.

Please give [3.6.2 Milestone 2 a try](https://groups.google.com/forum/#!topic/rabbitmq-users/df2RsO7jSYQ).

**Closed by michaelklishin** 2016-03-29 14:30 UTC
Labels: duplicate
