### ISSUE TITLE
Chocolatey releases

### ISSUE THREAD

**Issue by mribichich** [rabbitmq/rabbitmq-server#840] opened 2016-06-10 17:58 UTC
It would be great if you could release to chocolatey also.
There is already a package there but its way out of date

thanks!

**Comment by michaelklishin** [comment] 2016-06-10 17:59
Who maintains that package?

**Comment by siulung4073** [comment] 2016-06-10 18:02
For what it says in the package: [Robert Labrie](https://chocolatey.org/profiles/RobertLabrie)

[Chocolatey package](https://chocolatey.org/packages/rabbitmq)

**Comment by michaelklishin** [comment] 2016-06-10 18:05
If @robertlabrie would be interested in transferring package rights to our team we would consider it.

**Comment by siulung4073** [comment] 2016-06-10 18:08
That would be great, thanks!

**Comment by robertlabrie** [comment] 2016-06-10 18:33
I'm sorry I ignored everyone! Yes, I'd be happy to transfer. I changed job
and no longer work on this.

Does anyone know how?

**Comment by michaelklishin** [comment] 2016-06-10 21:02
@robertlabrie [Chocolatey docs](https://github.com/chocolatey/choco/wiki/PackageMantainerHandover) suggest you need to add us as a maintainer. Can you please add me (`mklishin <$> pivotal.io`) and our shared team email `team <$> rabbitmq.com`? I'm new to Chocolatey myself so maybe I need to sign up first?

**Comment by michaelklishin** [comment] 2016-06-10 21:24
@robertlabrie OK, I've signed up with both of the emails above. Please add us as maintainers or (if possible) co-owners of the package and we'll figure out the rest. Thank you!

**Comment by robertlabrie** [comment] 2016-06-10 22:11
Hi Michael,

I need your username(s), Choclatey doesn't lookup by email.

Also, I'm kind of glad to be handing this over to the vendor :)

Let me know your usernames and I'll take care of it.

**Comment by michaelklishin** [comment] 2016-06-10 23:47
@robertlabrie `rabbitmq` and `mklishin-pivotal`, thank you.

**Comment by robertlabrie** [comment] 2016-06-10 23:59
Hi Michael,

Ok, it's done. It says "pending approval", I don't know what that means,
but lets keep an eye on it and see if it resolves itself automatically.

If it's still pending on Monday then I'll drop a message on the Google
Group and try to find out what the scoop is.

**Comment by michaelklishin** [comment] 2016-06-11 08:55
It needed a confirmation from me, both accounts should be confirmed now.

Thank you, Robert! We should be able to take it from here.

On Sat, Jun 11, 2016 at 3:00 AM, robertlabrie <notifications@github.com>
wrote:

> Hi Michael,
>
> Ok, it's done. It says "pending approval", I don't know what that means,
> but lets keep an eye on it and see if it resolves itself automatically.
>
> If it's still pending on Monday then I'll drop a message on the Google
> Group and try to find out what the scoop is.
>
> On Fri, Jun 10, 2016 at 7:48 PM, Michael Klishin <notifications@github.com
> >
> wrote:
>
> > @robertlabrie <https://github.com/robertlabrie> rabbitmq and
> > mklishin-pivotal, thank you.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/rabbitmq/rabbitmq-server/issues/840#issuecomment-225321214
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AEVU5YrG71ss-3Yogpo6nfx7vQYoFqz7ks5qKfe2gaJpZM4IzLn2
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rabbitmq/rabbitmq-server/issues/840#issuecomment-225322541>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAEQoL-vXGOZXuD--JcB3lUuIfu3EXyks5qKfqAgaJpZM4IzLn2>
> .
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by robertlabrie** [comment] 2016-06-11 13:04
Thanks for taking it over. You can remove me as a maintainer.

Cheers,
Rob

**Comment by siulung4073** [comment] 2016-06-11 20:41
great thanks!

**Comment by michaelklishin** [comment] 2016-06-13 10:15
We will do a Chocolatey release of `3.6.3` once it is ready.

**Comment by mribichich** [comment] 2016-06-13 13:19
Excellent!

**Comment by michaelklishin** [comment] 2016-06-28 13:56
Package source is now at https://github.com/rabbitmq/chocolatey-package.

**Comment by michaelklishin** [comment] 2016-07-07 08:15
`3.6.3` is submitted for moderation.

**Comment by michaelklishin** [comment] 2016-07-08 13:11
[3.6.3 is up](https://chocolatey.org/packages/rabbitmq). Note that it requires using Erlang 18.x due to undocumented breaking changes in 19.0.

**Closed by michaelklishin** 2016-07-08 13:11 UTC
Labels: effort-low, pkg-windows
