### ISSUE TITLE
Logs on window inconsistent use of \ / in Path.

### ISSUE THREAD

**Issue by LindaLawton** [rabbitmq/rabbitmq-server#3149] opened 2021-06-25 08:27 UTC
I was just checking the logs and its strange that the` config file(s)` would have Linux slashes / and the rest of them are using windows \ .

```
 Starting RabbitMQ 3.8.17 on Erlang 24.0.2
 Copyright (c) 2007-2021 VMware, Inc. or its affiliates.
 Licensed under the MPL 2.0. Website: https://rabbitmq.com
2021-06-25 10:21:30.207 [info] <0.282.0> 
 node           : rabbit@DESKTOP-R0C0P2L
 home dir       : C:\windows\system32\config\systemprofile
 config file(s) : c:/Users/linda/AppData/Roaming/RabbitMQ/rabbitmq.config
 cookie hash    : aDFhdX6hHRC6KFNpSOR9Xg==
 log(s)         : c:/Users/linda/AppData/Roaming/RabbitMQ/log/rabbit@DESKTOP-R0C0P2L.log
                : c:/Users/linda/AppData/Roaming/RabbitMQ/log/rabbit@DESKTOP-R0C0P2L_upgrade.log
```

Side note

    rabbitmq-diagnostics.bat status

Seems to be consistent with its use of /'s at least

```
Node data directory: c:/Users/linda/AppData/Roaming/RabbitMQ/db/rabbit@DESKTOP-R0C0P2L-mnesia
Raft data directory: c:/Users/linda/AppData/Roaming/RabbitMQ/db/rabbit@DESKTOP-R0C0P2L-mnesia/quorum/rabbit@DESKTOP-R0C0P2L

←[1mConfig files←[0m

 * c:/Users/linda/AppData/Roaming/RabbitMQ/rabbitmq.config

←[1mLog file(s)←[0m

 * c:/Users/linda/AppData/Roaming/RabbitMQ/log/rabbit@DESKTOP-R0C0P2L.log
 * c:/Users/linda/AppData/Roaming/RabbitMQ/log/rabbit@DESKTOP-R0C0P2L_upgrade.log
```

Yes this is probably just me nitpicking.

**Comment by michaelklishin** [comment] 2021-06-25 08:43
They are retrieved differently. This has been the case for years and this is the first time I recall someone bringing this up.
I'm sorry but our team has much more pressing things to work on.

**Comment by lhoguin** [comment] 2021-06-25 09:41
It should be relatively trivial to make the handful that are using backslashes use slashes instead. Just call `filename:absname` where we are printing those paths. A PR would be unlikely to be rejected.

**Comment by LindaLawton** [comment] 2021-06-25 16:07
@michaelklishin  I'm really sorry that you are so busy please remember to stop and smell the roses sometimes.

@lhoguin this was more along the lines of the response I expected to get.   I never submit pull requests without first talking to the team on the project. Don't want to step on toes. I was going to offer to take care of it as it should be a quick fix.

**Comment by michaelklishin** [comment] 2021-06-28 10:31
@lhoguin we already do that: https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/src/rabbit_config.erl#L35-L43.

That value is then passed as is to `rabbit:config_locations/0` which is used by `rabbit:print_banner/0`.

**Comment by michaelklishin** [comment] 2021-06-28 10:38
@LindaLawton open source maintainers can choose to say "no" to things, features, and even minor bugs. 
After admitting that the issue is nitpicking and never stating your intent to contribute, you find it appropriate to treat those who honestly say "we likely won't work on this" with sarcasm.

It never ceases to amaze me how little appreciation open source maintainers get. Everyone thinks what they bring up
is important and yet 99% never contribute anything, just complain.

**Comment by michaelklishin** [comment] 2021-06-28 11:05
@lhoguin does #3152 look like what you had in mind?

We only produce OCI images for PRs, so in order to produce an easy-to-test Windows installer, we'd have to build a one-off manually or wait for the pipeline to do a full run after merging.

**Comment by LindaLawton** [comment] 2021-06-28 11:23
@michaelklishin I did not think it was sacrum. To me it sounded like you were to busy to deal with a minor issue.  Which was exactly what you said.  As I know how it is being overloaded on a project I attempted to "kindly" suggested you take a break sometimes.  

I have been using this project on and off for years 5+ I know what you guys do and respect immensely your work.   Which is why I was going to offer to deal with the minor issue.  I have unfortunately had issues in the past offering to help on OS projects. That's why I tend to tread lightly before offering my assistance and see what the response is.   Most projects just post back that they would welcome a PR.   

>Everyone thinks what they bring up is important and yet 99% never contribute anything, just complain.

May I suggest making people like me who come with small issues thinking that it could be a prefect first time contribution to a project I have been using for years.  Feel welcome would be a start.   

Please keep up the good work,  I wont bother you with simple issues again.

**Comment by michaelklishin** [comment] 2021-06-28 11:32
@LindaLawton OK, then I misinterpreted your comment. Sorry about that. 

You are welcome to report small issues, of course.
If you have interest in contributing, please state so. I wouldn't have closed this issue as a `wontfix` if I knew someone simply needs to learn where to start :)

**Closed** 2021-06-30 06:19 UTC
Labels: usability
