### ISSUE TITLE
Allow setting of multiple non-conflicting policies of same priority on queues/exchanges

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#841] opened 2016-06-10 18:01 UTC
Unless this is by design, I think when, for example, the following non-conflicting policies are defined, declaring queues should result in all of these being applied;

`rabbitmqctl set_policy ha-2-policy ".*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}' --apply-to queues --priority 0`

`rabbitmqctl set_policy lazy-policy ".*" '{"queue-mode":"lazy"}' --apply-to queues --priority 0`

`rabbitmqctl set_policy qml-policy  ".*" '{"queue-master-locator":"random"}' --apply-to queues --priority 0`

and only when policies are of the same **type** and **priority** should they be applied non-deterministically. Currently, in such a case, only a single policy is applied non-deterministically, regardless of there not being any possible conflicts amongst defined policies.

**Comment by michaelklishin** [comment] 2016-06-10 18:03
It is by design. How do we define if two policies have a conflict?

**Comment by Ayanda-D** [comment] 2016-06-10 18:08
Okay. I suppose if we can classify them, and if defined policies belong to the same class, they'd be applied in a non-deterministic manner.

**Comment by michaelklishin** [comment] 2016-06-10 18:09
They are applied in a deterministic manner: top priority wins, equal priorities are not supposed to be used.

**Comment by Ayanda-D** [comment] 2016-06-10 18:20
Okay cool. Maybe we should document this, that for example, if you want use a lazy queue or queue master distribution strategy, with mirroring policies, to only use declare arguments (and/or `rabbitmq.config` for queue master location). Although I'd have expected setting these as policies of equal priorities to also be possible, if possible via declare args.

**Comment by michaelklishin** [comment] 2016-06-13 10:14
I think we can explore a way to merge policies with equal priorities. This will be a moderately significant breaking change so can only go into `3.7.0`.

Another (related) feature request that goes with that is global (vhost-wide) policies for RabbitMQ-as-a-Service kind of environments.

**Comment by hairyhum** [comment] 2016-09-06 10:54
This issue is related to #930
In #930 is policies can be merged with "operator policies", but not with each other.
So there will be zero or one policy and zero or one operator policy, which will be merged for each queue.
Since we have the extensible merging mechanism and the UI for displaying effective policy definitions we can consider merging policies as well.

**Comment by michaelklishin** [comment] 2016-09-06 10:55
Merging policies will be a significant breaking change. I am currently not convinced than doing anything beyond #930 is worth it. I suggest that we close it and wait for feedback from those who needed #930 the most.

**Closed by michaelklishin** 2016-09-06 10:55 UTC
Labels: effort-medium, enhancement, no-decision
