### ISSUE TITLE
Channel closed due to partial tx completion on 3.8.3

### ISSUE THREAD

**Issue by ppogorzelski** [rabbitmq/rabbitmq-server#2318] opened 2020-04-17 08:06 UTC
I got an IO excpetion when committing on an autorecovering channel:

> java.io.IOException: null
>         at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:116)
>         at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:112)
>         at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:134)
>         at com.rabbitmq.client.impl.ChannelN.txCommit(ChannelN.java:1318)
>         at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.txCommit(AutorecoveringChannel.java:503)
>         at com.ligertrading.nebula.common.rabbitmq.internal.TransactionalChannel.publish(TransactionalChannel.java:49)

This is a corresponding node entry:

> 2020-04-15 22:35:40.235 [error] <0.611.272> Error on AMQP connection <0.611.272> (127.0.0.1:37220 -> 127.0.0.1:5672, vhost: '/', user: 'nebula', state: running), channel 1:
>  operation basic.publish caused a connection exception channel_error: "unexpected command while processing 'tx.commit'"

It causes the channel to close and subsequent publishes throw AlreadyClosedException:

> com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - partial tx completion, class-id=90, method-id=20)
>         at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:209)
>         at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:338)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:686)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:668)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:658)
>         at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:192)

The problem surfaced after a move from 3.5.6 to 3.8.3. It happens periodically (once every couple of M messages) on 3.8.3 nodes wheres 3.5.6 are just fine. Looks like some server error recovery changed in between and nodes are not able to handle this situation gracefully any longer.

**Comment by michaelklishin** [comment] 2020-04-17 10:33
There are 4.5 years between 3.5.6 and 3.8.3 so let's refrain from speculating.

Is there a code snippet we can use to reproduce?

**Comment by michaelklishin** [comment] 2020-04-17 10:41
The error is logged [by this function](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_channel.erl#L1288) which has an explanation:

 * The spec prohibits clients from sending methods while waiting for a pending synchronous command (such as `tx.commit` which has a response such as `tx.commit-ok`)
 * RabbitMQ generally allows such "unintentional pipelining" except for when a transaction has to be committed on the same channel

So this is by design and it has nothing to do with connection recovery. If you post your code that involves `ChannelN.txCommit` we potentially would be able to tell what leads to this scenario. It could be concurrent use a of shared channel ([something RabbitMQ clients do not support](https://www.rabbitmq.com/api-guide.html#concurrency)) or something else. We do not guess on this team.

Moving this to discussions.

**Closed by michaelklishin** 2020-04-17 10:41 UTC
