### ISSUE TITLE
Slow increase seen in message store index in 3.6.2M3

### ISSUE THREAD

**Issue by spatula75** [rabbitmq/rabbitmq-server#740] opened 2016-04-11 15:22 UTC
During the investigation of rabbitmq-management#166 and 173, and running the [simload script](https://github.com/rabbitmq/rabbitmq-management/issues/166#issuecomment-206699217), we noticed a slow increase in the size of the message store index over time, which was not reclaimed after the script stopped running, all the queues emptied out, and all garbage collection was run manually.

However, not being familiar with rabbitmq-server internals, there are certainly reasons this might happen that don't involve actual memory leaking; for example, the automatic resizing of a data structure to be able to accommodate the load for which it wouldn't be worthwhile to down-size later after the load ceased.

The total increase seen was on the order of about 24 MB in about a day of running three instances of simload.rb, to a total of about 26 MB.

In any case, it might be something worth investigating, and if it's indeed not an actual leak, closing :)

**Comment by dcorbacho** [comment] 2016-04-11 16:25
I have seen the same message store index increasing while fixing the mentioned bugs - without any messages in the system - but that memory stops increasing and drops every 4 hours.

<img width="642" alt="screen shot 2016-04-06 at 17 49 34" src="https://cloud.githubusercontent.com/assets/646577/14434232/b16d6404-0009-11e6-8188-a7af52c95cd2.png">

**Comment by spatula75** [comment] 2016-04-11 17:05
I do not see the same oscillation on our cluster without any load, nor do I see any further rise without load; rather, it's holding steady at the size to which the index had grown.

**Comment by spatula75** [comment] 2016-04-11 17:06
I also haven't (yet) seen the index grow beyond 26MB.  Not sure if that's a magic number or just coincidental, of course.

**Comment by michaelklishin** [comment] 2016-04-11 17:06
Indexes are flushed to disk every N entries, keep that in mind.

**Comment by spatula75** [comment] 2016-04-12 23:15
26 turns out not to be a magic number.  It also looks like we might be seeing the index size creep at least as far back as our production 3.5.7 cluster, but anecdotally it looks vaguely like the creep might be faster in 3.6.2M3, but that's just a general observational sense, not anything I can prove with hard data.

**Comment by spatula75** [comment] 2016-06-01 17:55
Just FYI, we still see this in the 3.6.2 final release when rates mode is set to 'basic' but it does not seem to be significant when rates mode is set to 'none.'  Also I noticed just now that should have opened this against rabbitmq-management rather than rabbitmq-server.

**Comment by michaelklishin** [comment] 2016-06-01 19:12
@spatula75 since message rate mode do not affect message store, that sounds like a stats collection issue. We had fixed something similar with socket count in the past.

**Comment by spatula75** [comment] 2016-06-01 20:01
One thing I've verified does _not_ seem to affect the rate of increase is just creating a lot of channels and closing them (with basic mode enabled).  If I have some time, I'll see if publishing lots of messages affects it today or tomorrow.  (I somewhat suspect it's message that are doing it.)

**Comment by michaelklishin** [comment] 2016-06-01 20:06
Having messages enqueued is certainly a requirement to have any messages in the message store, in fact, messages larger than 4kB (by default). But it is not the message store that reports incorrect values, most likely.

**Comment by spatula75** [comment] 2016-06-01 20:17
I think I might be conflating two things here too now that I re-read the history.  Most of the increase we're seeing is on the management database side of things; the message store increase is insignificant by comparison.

**Comment by hairyhum** [comment] 2016-06-08 11:29
@spatula75 can you try `3.6.3 milestone1` and tell if you can see the same increase?
There was a memory leak in stats collector, which let to `binary` memory usage increase.

**Comment by hairyhum** [comment] 2016-06-10 11:39
@spatula75 regarding message store index, it's being filled with records about messages in transient message store file. This file is being GCed once it reach `msg_store_file_size_limit` and message store index table is being cleared. 
I'm not sure why `simload.rb` sends this messages to disk but it should not be a leak, because index is being cleared eventually. 
But it could take up to 65MB of RAM for message store index table for 16MB file (default file size limit), which is still not good.

**Comment by michaelklishin** [comment] 2016-06-10 11:46
For those following along, keep in mind that messages smaller than 4096 bytes by default are not even sent to the message store: they are stored in the queue index directly.

@hairyhum that part is pluggable and we've been considering using a disk-based store for a while. There was a LevelDB-backed plugin at some point. The downsides are predictable: lower throughput (for messages that go to message store) and the can of worms that is using platform-specific native extensions.

I think we can close this issue and file one for a disk-based message store index.

**Closed by michaelklishin** 2016-06-10 11:46 UTC
Labels: no-decision

**Comment by michaelklishin** [comment] 2016-06-27 08:38
https://github.com/rabbitmq/rabbitmq-server/issues/839 addresses the root cause. We intend to include it into `3.6.4`.
