### ISSUE TITLE
3.12: CQ with TTL seems to be spinning in place after a restart

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-server#7939] opened 2023-04-19 14:24 UTC
### Describe the bug

Hi,

I was testing some changes and I was using the AMQP 1.0 plugin to publish into a Classic Queue, however I do not think this issue is related to the AMQP 1.0 plugin. 

Anyway, this is just a heads up if maybe you are experiencing the same. 

It can not be reproduced consistently, but 

### Reproduction steps

1. Checkout main
2. Use Erlang 25.0.4
1. Set up a classic queue
3. Add a TTL policy of 30 seconds
4. Restart RabbitMQ
5. Use publish confirms but do not actually wait for confirms except at the end of the run
6. Publish 400 000 reasonably small messages with some headers
7. Wait for confirms, disconnect
8. Wait a few seconds 
9. Publish 400 000 reasonably small messages with some headers (This will trigger the issue probably)
10. Wait for confirms (it will time out)
11. Repeat from 4 if it did not get stuck.

Observe the following: 
1. Mgmt interface shows 0 messages
2. Channel shows 400 000 unconfirmed messages
3. It takes about 2-3 minutes to churn through the 400k messages on my macbook. 

![kép](https://user-images.githubusercontent.com/923194/233105501-bebb5ac4-56ee-4b1a-ba84-77c4d3428be6.png)

On RabbitMQ Top, it is visible that the Erlang Mailbox / Gen Server 2 is full with 400k messages. 

The queue is spinning in these stacktraces: 

```
[{prim_file,read_info_1,3,[]},
 {file_handle_cache,with_handle,2,[{file,"file_handle_cache.erl"},{line,572}]},
 {rabbit_file,file_size,1,[{file,"rabbit_file.erl"},{line,52}]},
 {rabbit_queue_index,load_segment,2,
                     [{file,"rabbit_queue_index.erl"},{line,1239}]},
 {rabbit_queue_index,segment_entries_foldr,3,
                     [{file,"rabbit_queue_index.erl"},{line,1224}]},
 {rabbit_queue_index,read_bounded_segment,5,
                     [{file,"rabbit_queue_index.erl"},{line,1206}]},
 {rabbit_queue_index,read,3,[{file,"rabbit_queue_index.erl"},{line,500}]}]

```

```
[{gen,do_call,4,[{file,"gen.erl"},{line,237}]},
 {gen_server2,call,3,[{file,"gen_server2.erl"},{line,342}]},
 {file_handle_cache,with_handle,2,[{file,"file_handle_cache.erl"},{line,571}]},
 {rabbit_file,file_size,1,[{file,"rabbit_file.erl"},{line,52}]},
 {rabbit_queue_index,load_segment,2,
                     [{file,"rabbit_queue_index.erl"},{line,1239}]},
 {rabbit_queue_index,segment_entries_foldr,3,
                     [{file,"rabbit_queue_index.erl"},{line,1224}]},
 {rabbit_queue_index,read_bounded_segment,5,
                     [{file,"rabbit_queue_index.erl"},{line,1206}]},
 {rabbit_queue_index,read,3,[{file,"rabbit_queue_index.erl"},{line,500}]}]
```

```
[{array,set,3,[{file,"array.erl"},{line,575}]},
 {rabbit_queue_index,parse_segment_publish_entry,5,
                     [{file,"rabbit_queue_index.erl"},{line,1281}]},
 {rabbit_queue_index,segment_entries_foldr,3,
                     [{file,"rabbit_queue_index.erl"},{line,1224}]},
 {rabbit_queue_index,read_bounded_segment,5,
                     [{file,"rabbit_queue_index.erl"},{line,1206}]},
 {rabbit_queue_index,read,3,[{file,"rabbit_queue_index.erl"},{line,500}]},
 {rabbit_variable_queue,maybe_deltas_to_betas,3,
                        [{file,"rabbit_variable_queue.erl"},{line,2612}]},
 {rabbit_variable_queue,fetch_from_q3,1,
                        [{file,"rabbit_variable_queue.erl"},{line,2570}]},
 {rabbit_variable_queue,queue_out,1,
                        [{file,"rabbit_variable_queue.erl"},{line,1551}]}]
```

### Expected behavior

Queue accepts the messages reasonably quickly. 

### Additional context

This is on `main`, so it may be something under development.

It may be that the expiring messages interact with the incoming messages in a bad way.

**Comment by luos** [comment] 2023-04-20 06:53
I was not able to reproduce it with CQv2 in the few tries I tried. Usually with V1 it is about 50% that it happens to me.

**Comment by lhoguin** [comment] 2023-04-24 12:13
I can reproduce. CQv1 seems to be super inefficient with TTLs on main. Smaller steps:

1. Checkout main
1. Use any Erlang compatible with main
1. Add a global TTL policy of 30 seconds (30000) in management
1. Send many messages with perf-test for about 10s `-x 1 -y 0 -u v1` (confirms don't matter)
1. Stop it and wait a few seconds
1. Observe a lot of work being done in top or observer_cli

CQv1 seems to spend a lot of time reading messages from segment files.

The problem probably exists in 3.11 when lazy queues are used with CQv1.

**Comment by lhoguin** [comment] 2023-04-25 07:56
I have opened https://github.com/rabbitmq/rabbitmq-server/pull/7980 with the fix for this issue. Please repeat your steps with the branch `lh-cqv1-ttl` instead of `main`. The queue will still do a lot of work but it shouldn't get unresponsive anymore.

**Comment by michaelklishin** [comment] 2023-04-25 14:08
@luos can you please give #7980 a try? We are looking to ship a 3.12.0 RC ASAP.

**Closed** 2023-04-26 06:33 UTC
Labels: bug
