### ISSUE TITLE
RPMs for Red Hat 8 and CentOS 8

### ISSUE THREAD

**Issue by nih0** [rabbitmq/rabbitmq-server#2137] opened 2019-10-11 07:08 UTC
Currently there are "no" packages for el/8 on packagecloud and bintray. 

I tried the el/7 packages(rabbitmq-erlang, rabbitmq_rabbitmq-server) and they work good, as expected :)

I just had to change the yum/dnf repos configuration to point to the el/7 repo on packagecloud to get it running.

I documented my changes on the mailing list: https://groups.google.com/d/msg/rabbitmq-users/1u8W-1Zq0sw/P_DhwNIwBwAJ

**Comment by michaelklishin** [comment] 2019-10-11 13:49
Duplicate of https://github.com/rabbitmq/rabbitmq-server-release/issues/109.

**Closed by michaelklishin** 2019-10-11 13:49 UTC
