### ISSUE TITLE
Diskspace incorrectly shows as 0 

### ISSUE THREAD

**Issue by bartdircx** [rabbitmq/rabbitmq-server#5681] opened 2022-08-30 14:11 UTC
issue https://github.com/rabbitmq/rabbitmq-server/issues/4003 has been closed but I have an identical error on one rabbitmq server in our cluster.  
Our setup:
- RabbitMQ v 3.10.2
- Erlang 25.0
- Windows Server 2019 (no service pack)

![image](https://user-images.githubusercontent.com/30413247/187403116-a1e308d0-529b-438a-aa5b-008d6569a541.png)

rabbitmqctl status
Status of node rabbit@P-EXT-BAT094 ...
Error:
:badarith

logging found
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> Command timed out: 'powershell.exe -NoLogo -NoProfile -NonInteractive -Command (Get-PSDrive d).Free'
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> ** Generic server rabbit_disk_monitor terminating
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> ** Last message in was try_enable
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> ** When Server state == {state,"d:/rabbitmq/db/rabbit@P-EXT-BAT094-mnesia",
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>                                50000000,undefined,100,10000,undefined,false,
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>                                false,10,120000}
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> ** Reason for termination ==
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> ** {could_not_determine_disk_free,
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>        [{rabbit_disk_monitor,get_disk_free,2,
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>             [{file,"rabbit_disk_monitor.erl"},{line,254}]},
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>         {rabbit_disk_monitor,internal_update,1,
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>             [{file,"rabbit_disk_monitor.erl"},{line,216}]},
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>         {rabbit_disk_monitor,enable,1,
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>             [{file,"rabbit_disk_monitor.erl"},{line,355}]},
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>         {rabbit_disk_monitor,handle_info,2,
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>             [{file,"rabbit_disk_monitor.erl"},{line,164}]},
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>         {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,1120}]},
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>         {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1197}]},
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>         {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> 
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>   crasher:
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     initial call: rabbit_disk_monitor:init/1
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     pid: <0.28196.8>
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     registered_name: rabbit_disk_monitor
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     exception exit: could_not_determine_disk_free
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>       in function  rabbit_disk_monitor:get_disk_free/2 (rabbit_disk_monitor.erl, line 254)
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>       in call from rabbit_disk_monitor:internal_update/1 (rabbit_disk_monitor.erl, line 216)
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>       in call from rabbit_disk_monitor:enable/1 (rabbit_disk_monitor.erl, line 355)
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>       in call from rabbit_disk_monitor:handle_info/2 (rabbit_disk_monitor.erl, line 164)
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>       in call from gen_server:try_dispatch/4 (gen_server.erl, line 1120)
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>       in call from gen_server:handle_msg/6 (gen_server.erl, line 1197)
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     ancestors: [rabbit_disk_monitor_sup,rabbit_sup,<0.229.0>]
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     message_queue_len: 0
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     messages: []
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     links: [<0.429.0>]
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     dictionary: []
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     trap_exit: false
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     status: running
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     heap_size: 2586
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     stack_size: 28
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>     reductions: 26951
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8>   neighbours:
2022-08-30 10:00:15.977000+02:00 [error] <0.28196.8> 
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>     supervisor: {local,rabbit_disk_monitor_sup}
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>     errorContext: child_terminated
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>     reason: could_not_determine_disk_free
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>     offender: [{pid,<0.28196.8>},
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>                {id,rabbit_disk_monitor},
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>                {mfargs,{rabbit_disk_monitor,start_link,[50000000]}},
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>                {restart_type,{transient,1}},
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>                {shutdown,300000},
2022-08-30 10:00:15.977000+02:00 [error] <0.429.0>                {child_type,worker}]

the command which times out runs perfectly when started manually

**Comment by lukebakken** [comment] 2022-08-30 14:58
Duplicate of #4003

**Closed by lukebakken** 2022-08-30 14:58 UTC
