### ISSUE TITLE
Consumer is lost after HA queue failover

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#641] opened 2016-02-20 12:27 UTC
We have following funny scenario:
- consumer listening to several mirrored queues and connected to node-3
- mirrored queue master is on node-1
- node-1 dies
- slave on node-2 is promoted
- node-3 does `erlang:disconnect('node-2')`
- node-3 does `rabbitmqctl forget_cluster_node node-2`
- slave on node-3 is promoted
- node-2 is restarted and rejoined with node-3

Consumer lived through all this turmoil and continues to receive some messages from queues it subcribed to. But at least one of the queues stops sending messages to this consumer.

`rabbitmqctl list_channels name pid consumers` shows that this channel has 3 consumers, but `rabbitmqctl list_consumers` finds only 2.

With help of the `sys:get_state/1` and profanities I've found that `consumer_mapping` of channel contains reference to stale queue pid. And it's really stale - it's from the previous instance of erlang VM on node-2.

There is nothing suspicious in logs and I'm not sure where to look further (except the source code :smile:).

Is there some things I should look into for additional info while I still have access to this cluster?

**Comment by binarin** [comment] 2016-02-20 15:51
So the channel in question:
1) Has no reference to the bad queue in `queue_names` and `queue_monitors`.
2) Retains references to the bad queue in `queue_consumers` and `consumer_mapping`.

It shows us that channel received 'DOWN' message and at least partially handled it in its `handle_info/2` callback. But `handle_consuming_queue_down/2` failed to do its job during that time.

**Comment by wong000** [comment] 2018-08-14 08:16
Has this problem been solved?

**Comment by lukebakken** [comment] 2018-08-14 12:53
@wong000 - why do you ask? Did you see the same thing? Do you have reliable steps to reproduce this issue?

I did some research and it looks like there is no guaranteed way to reproduce this issue. If you can provide one, please do.

**Comment by michaelklishin** [comment] 2018-08-14 13:01
We don't have a way to reproduce and the issue is over 2 years old => closing. Please post all related findings to rabbitmq-users first and we'd be happy to file a new issue once/if enough evidence and data is gathered.

**Closed by michaelklishin** 2018-08-14 13:01 UTC

**Comment by wong000** [comment] 2018-08-15 02:53
I have just met a very similar phenomenon.But it can't be reproduced.
There are two nodes in the cluster. Node1 dies（unknown reason），Node2 provides services.，But one consumer can't register with node2. The queue q-reports-plugin can not find this consumer，so node2 can not push the message to it.
