### ISSUE TITLE
RabbitMQ crashes

### ISSUE THREAD

**Issue by chernser** [rabbitmq/rabbitmq-server#1165] opened 2017-03-29 11:27 UTC
=== Carefully read before closing critical bug.  === 

There is published which produces a lot messages.
There is consumer which consume messages. 
When messages more that consumer can consume - rabbitmq stores them in mnesia. 
If consumer dies, rabbitmq get memory high watermark alert and crashes. 
if consumer continue working, rabbitmq doesn't crash. 

Once again, rabbitmq crashes when consumer dies when queue has a lot messages.
Rabbitmq doesn't crash if there is no consumer at all. 

Quite strange, isn't it? 

==== Initial bug report === 

I have direct exchange and queue.
I have simple client source

Connects to rmq servers
Declares queue and exchange
calls basic consume, but do not consume them
publishes 10k messages
closes connection
I have virtual host with 1Gb RAM

When script ends and closes connection, rabbitmq crashes (just terminated) with next log:

=INFO REPORT==== 29-Mar-2017::11:00:06 ===
vm_memory_high_watermark set. Memory used:881321872 allowed:787377356
=WARNING REPORT==== 29-Mar-2017::11:00:06 ===
memory resource limit alarm set on node rabbit@inf.
*** Publishers will be blocked until this alarm clears ***

After that I need to restart the rabbitmq.

My test client can produce 30k messages and more, but rabbitmq keeps running, until connection is closes.

**Comment by michaelklishin** [comment] 2017-03-29 11:28
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/1164. Your publishes instructs RabbitMQ to keep 10K of 100kB messages (published as transient) in memory with only 1 GB available and 40% of that available to RabbitMQ.

**Closed by michaelklishin** 2017-03-29 11:28 UTC

**Comment by chernser** [comment] 2017-03-29 11:30
@michaelklishin the problem is in why RabbitMQ crashes when consumers disconnect. What is not clear? 
Why RabbitMQ doesn't crash when there is no consumer?

**Comment by michaelklishin** [comment] 2017-03-29 11:30
@chernser filing the same issue while ignoring our responses is not going to get you far. Fix your publisher to use durable queues and persistent messages, or use a [limited consumer QoS](http://www.rabbitmq.com/confirms.html), or your expectations.

**Comment by michaelklishin** [comment] 2017-03-29 11:32
@chernser I [have explained](https://github.com/rabbitmq/rabbitmq-server/issues/1164#issuecomment-290060479) why but you aren't listening or trying to understand what is really going on.

**Comment by michaelklishin** [comment] 2017-03-29 11:33
If you really investigated how persistence works ([docs](http://www.rabbitmq.com/memory.html), [internals](https://github.com/rabbitmq/internals)) you would have known that messages are not stored in Mnesia.

**Comment by michaelklishin** [comment] 2017-03-29 11:40
In addition, your consumer [consumes without a QoS on its channel](https://gist.github.com/chernser/8f79a0e103354edad87d71e24b5c52e3#file-rabbittest-py-L30), which tells RabbitMQ to deliver messages to it as quickly as possible, and that means they are either kept in RAM or loaded from disk eagerly.

**Comment by michaelklishin** [comment] 2017-03-29 12:37
The has drawn [quite a longer answer on rabbitmq-users](https://groups.google.com/d/msg/rabbitmq-users/Sl8So_xf4Vg/6sCJUJRDGAAJ).
