### ISSUE TITLE
pg2_table can continuously grow when queues are using federation policy and are auto expiring

### ISSUE THREAD

**Issue by johanrhodin** [rabbitmq/rabbitmq-server#2497] opened 2020-11-08 02:56 UTC
rabbitmq-users list (https://groups.google.com/g/rabbitmq-users/c/J8-UbI9Ri6U/m/9GkR-JDnBgAJ).

The pg2table can grow without boundary in a case where queues are auto created and deleted, and have a federation policy.
 
To reproduce:
- Create a queue (or exchange) policy: `federation-upstream-set: all`.
- Create unique queues, publish a message to them, and then let the queue expire.
- Watch pg2table grow.

A script to reproduce: https://gist.github.com/johanrhodin/8a259e2a3b750159fcea9fea32fb41b2

Verify:
```
$ rabbitmqctl eval 'ets:info(pg2_table,size).'
26
# Run script ./pg2table.rb
$ rabbitmqctl eval 'ets:info(pg2_table,size).'
4865
```

**Comment by lukebakken** [comment] 2020-11-09 18:47
Hello, thanks for the report.

Could you please script the creation of the federation policy as well? Use the HTTP API or `rabbitmqadmin`. The reason I ask is so that we are using the _exact_ same steps as you.

**Comment by johanrhodin** [comment] 2020-11-09 22:53
This is a curl command to put the federation policy:
```
curl -u xuyjpuxl:PASSWD -H "content-type:application/json" \
-XPUT  https://server-name.rmq.cloudamqp.com/api/policies/xuyjpuxl/fedonly \
-d '{"pattern":".", "definition": {"federation-upstream-set":"all"}, "priority":0, "apply-to": "all"}'
```

**Comment by lukebakken** [comment] 2020-11-10 00:21
I still can't reproduce this. No matter how many times I run `pg2table.rb`, the size of the `pg2_table` does not increase:

```
$ while true; do ./sbin/rabbitmqctl -n rabbit@localhost eval 'ets:info(pg2_table,size).'; sleep 1; done                                                                                                                                                                         
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20                                                                                                                                                                                                                                                                              
20
```

Here's how I'm doing my test:
* Start RabbitMQ from the `master` code using Erlang 23.1.2. These plugins are enabled: `rabbitmq_management rabbitmq_top rabbitmq_federation rabbitmq_federation_management`.
* Run the `rabbitmqctl eval` command in a loop as shown.
* Run the `curl` command to create the policy. *NOTE:* I do not have any federation links defined. I only am applying the policy as instructed here.
* Run `pg2table.rb` several times.

Please let me know if I'm missing any steps. I will close this issue for now but will keep an eye on follow-up responses and I will re-open it _if_ I can reproduce the issue.

**Comment by johanrhodin** [comment] 2020-11-10 04:56
Here's how I'm doing my test:

- RabbitMQ 3.8.9, Erlang 23.1
The following plugins enabled:
```
rabbitmq-plugins list --enabled
Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@test-big-swan-01
 |/
[E*] rabbitmq_consistent_hash_exchange 3.8.9
[E*] rabbitmq_event_exchange           3.8.9
[E*] rabbitmq_federation               3.8.9
[E*] rabbitmq_federation_management    3.8.9
[E*] rabbitmq_management               3.8.9
[E*] rabbitmq_shovel                   3.8.9
[E*] rabbitmq_shovel_management        3.8.9
```
- Run `rabbitmqctl eval 'ets:info(pg2_table,size).';` to check size initially. (26 in my case)
- Run curl command to get the policy for the vhost
- Run the script
- Run `rabbitmqctl eval 'ets:info(pg2_table,size).';` to check size after. (4745 in my case after first run, 9714 after second, 14684 after third and 19655 after the fourth.)

In each run I verify that the queues are created and policy applied (it can takes a few seconds to apply policies)
<img width="1216" alt="queues-with-messages-policy-applied" src="https://user-images.githubusercontent.com/460369/98629446-7d960580-22de-11eb-889f-0eb28469dfce.png">

<img width="873" alt="queue-with-exclusive-ttl-exipre-1-message-expired" src="https://user-images.githubusercontent.com/460369/98629419-6b1bcc00-22de-11eb-8d2b-2bc550c95175.png">

**Comment by johanrhodin** [comment] 2020-11-10 04:59
I've modified the script a bit, just creating 1 queue, publish a message to it, wait for it to expire, is enough.
https://gist.github.com/johanrhodin/8a259e2a3b750159fcea9fea32fb41b2

This is the entry that's added: 
``` 
{{group,
      {rabbit_federation_queue,
          {resource,<<"axjvzdid">>,queue,
              <<"amq.gen-yDb79kvRuEW_zD_i-lSv8A">>}}}},
```

**Comment by lukebakken** [comment] 2020-11-10 14:15
Thank you for the updated script and reproduction instructions. I can now reproduce the issue. I'm still using the same set of plugins as my original test description.

**Comment by michaelklishin** [comment] 2020-11-10 15:45
@lukebakken can this be https://github.com/rabbitmq/rabbitmq-federation/pull/119 which was merged for `3.8.10`?

**Comment by lukebakken** [comment] 2020-11-10 16:02
@michaelklishin no, because I can reproduce using `master`.

**Comment by dcorbacho** [comment] 2020-11-18 12:57
Thanks @johanrhodin, there is a PR fixing it. We were leaking entries on the pg2 table in two situations:

1. No upstream is present but the queue matches the federation pattern - reported here
2. A federation queue link is deleted

These are two different fixes that have been addressed in https://github.com/rabbitmq/rabbitmq-server/pull/2649

**Closed** 2020-11-18 17:25 UTC
Labels: bug, rabbitmq-federation
