### ISSUE TITLE
There is no possibility to forget_cluster_node with stopped RabbitMQ broker.

### ISSUE THREAD

**Issue by mr-yuri** [rabbitmq/rabbitmq-server#348] opened 2015-10-07 16:25 UTC
I have 2 nodes: ws and ws-clone

     cat  /etc/rabbitmq/rabbitmq.config
          .....
     {cluster_partition_handling, pause_minority}
.....
ws visible via ssh, broker on node "ws" is stopped due to pause minority
ws-clone in poweroff

[root@ws 16:51:41 ~]# rabbitmqctl cluster_status
Cluster status of node rabbit@ws ...
[{nodes,[{disc,[rabbit@ws,'rabbit@ws-clone']}]}]

from "ws" node I try to perform forget_cluster_node

[root@ws 16:48:40 ~] # rabbitmqctl forget_cluster_node rabbit@ws-clone
Removing node 'rabbit@ws-clone' from cluster ...
Error: {offline_node_no_offline_flag,"You are trying to remove a node from an offline node. That is dangerous, but can be done with the --offline flag. Please consult the manual for rabbitmqctl for more information."}

with --offline flag

[root@ws 16:48:40 ~] # rabbitmqctl forget_cluster_node --offline rabbit@ws-clone
Removing node 'rabbit@ws-clone' from cluster ...
  * Impersonating node: rabbit@ws...Error: {badmatch,
           {error,
               {shutdown,
                   {child,undefined,net_sup_dynamic,
                       {erl_distribution,start_link,[[rabbit@ws,shortnames]]},
                       permanent,1000,supervisor,
                       [erl_distribution]}}}}

/var/log/rabbitmq/rabbit@ws.log is empty

**Comment by Ayanda-D** [comment] 2015-10-12 18:32
Currently having a look at this. Produced the same problem with a 2 node cluster (e.g. `node1` and `node2`) and simulating an `offline` node by stopping the rabbit application (& not terminating the node); 
`$> rabbitmqctl -n rabbit@node1 stop_app` (which essentially is the effect of `pause_minority`), and executing `forget_cluster_node` from the `offline` node;
`$> rabbitmqctl -n rabbit@node1 forget_cluster_node --offline rabbit@node2`.

**Comment by Ayanda-D** [comment] 2015-10-14 18:41
findings thus far;
- when `forget_cluster_node --offline` is executed, an attempt to impersonate the offline node (`node1` or `ws` from above examples) is done.
- this by first stopping the `temp` node started by `rabbitmqctl` or switching to non-distributed, i.e. resulting in `nonode@nohost` - default shell, followed by an attempt to impersonate the executing offline node using `net_kernel:start([Name, NameType])`. Expected result of this action is a change from `nonode@nohost` to start up of the impersonation node where all native operations to forget the specified cluster node (`node2` or `ws-clone`) will be executed from.
- problem is failure in starting the impersonating node with net_kernel:start/1.
- an `offline` node, for example resulting from `pause_minority` partition handling, is not a terminated node. its just not visible to other cluster nodes and the rabbit application won't be running.
- this means that the `epmd` process on the host of the offline node still has the node name of the `offline` node registered, and attempts to impersonate this node by executing `net_kernel:start/1` result in a conflicts.
- for now, i think for a node to be truely `offline`, even outside the scope of rabbit cluster nodes & connecting clients, also means having its name not registered by local running `epmd` process - however no conclusions drawn yet

**Comment by Ayanda-D** [comment] 2015-10-15 15:08
hello @dumbbell. can you please have a read at what I have so far for this issue, and share your thoughts and advice. i'm not sure how impersonating an offline node on its host would be possible if its name is still be registered in `epmd` daemon. this seems to be the cause of the problem.

**Comment by dumbbell** [comment] 2015-12-03 14:11
Sorry, I totally missed the notification...

I didn't read the code but your analysis is sensible. I agree that rabbitmqctl should check if the node it wants to impersonate is actually running, no matter if RabbitMQ is started or not. For instance, in the case of some pause modes, even if RabbitMQ is stopped, there is a process checking the cluster to determine when to restart RabbitMQ. I believe rabbitmqctl shouldn't mess with the database with this background process running: the user should explicitely stop the node first.

**Comment by Ayanda-D** [comment] 2015-12-03 16:57
@dumbbell thanks for this. & okay, opening separate issue for rabbitmqctl to check if node to be impersonated is  actually running or not, despite status of rabbit application (which will make what's been reported here a forbidden operation).

**Comment by michaelklishin** [comment] 2016-01-05 16:26
@Ayanda-D do you think there's more that we can do for this than https://github.com/rabbitmq/rabbitmq-server/issues/470? or should we close this?

**Comment by Ayanda-D** [comment] 2016-01-05 16:32
@michaelklishin #470 should be a sufficient fix for this issue. We can go ahead and close this :)

**Comment by michaelklishin** [comment] 2016-01-05 16:32
:+1:

**Closed by michaelklishin** 2016-01-05 16:32 UTC

**Comment by moriyoshi** [comment] 2016-05-02 06:22
I was under the same circumstances (was stuck with exactly the same error message) and there shouldn't have been such a conflict that is described in https://github.com/rabbitmq/rabbitmq-server/issues/348#issuecomment-148151726, because there were no running node (i.e. no epmd processes were running could not be reached) other than the last survived node.

Looking at the thread in [rabbitmq-users](https://groups.google.com/forum/#!topic/rabbitmq-users/yptwODh5s7c) likely started by @mr-yuri,  he has had the identical problem, which is different from the one addressed eventually in #470.
