### ISSUE TITLE
TypeError on Management UI vhost page

### ISSUE THREAD

**Issue by Zeeeeta** [rabbitmq/rabbitmq-server#7470] opened 2023-03-01 04:29 UTC
RabbitMQ: 3.11.9
Erlang: 25.1.2
OS: RHEL 8.7

![image](https://user-images.githubusercontent.com/26813698/222044818-0347bf5e-0656-4487-be1b-503a10b85775.png)
![image](https://user-images.githubusercontent.com/26813698/222044904-bab491d5-0a24-41fa-8730-6991a8336fd1.png)

It is almost a default setup.
I have got the js error when visting the "/" vhost page
TypeError: Cannot read properties of undefined (reading 'length')

Please help.

**Comment by michaelklishin** [comment] 2023-03-01 04:32
Duplicate of #7301. Use CLI tools for now.

**Closed** 2023-03-01 04:32 UTC
