### ISSUE TITLE
Make background GC runner more configurable

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1026] opened 2016-11-08 13:01 UTC
See [this mailing list patch](https://groups.google.com/forum/#!topic/rabbitmq-users/gdqLpdWbop0) and its effect observations in a production system.

We should

 * Make the "ideal interval" configurable
 * Make disabling background GC runner possible

**Comment by kjnilsson** [comment] 2016-11-24 10:51
Whilst investigating something else I noticed this pattern on  a single rabbit node with 10000 idle queues.

<img width="687" alt="screenshot 2016-11-24 09 51 09" src="https://cloud.githubusercontent.com/assets/1180564/20595546/39d264e0-b232-11e6-9db7-af3de0bee715.png">

I haven't confirmed that it is caused by `background_gc` but the interval is in line with the default `IDEAL_INTERVAL`. Will try to test with the patch applied and `background_gc` disabled.

**Comment by acogoluegnes** [comment] 2016-11-28 14:20
Closed by https://github.com/rabbitmq/rabbitmq-server/pull/1039.

**Closed by acogoluegnes** 2016-11-28 14:20 UTC
Labels: effort-low, enhancement
