### ISSUE TITLE
RabbitMQ 3.10 classic queue v2 + Lazy policy cause a queue to crash

### ISSUE THREAD

**Issue by 3hedgehogs** [rabbitmq/rabbitmq-server#5252] opened 2022-07-18 12:10 UTC
I'm moving a problem from google group here.

I see permanent crash classical queue v2 (new in 3.10 version of RabbitMQ) if **lazy** policy is enable for it at the moment of reading from it.

To reproduce a problem a version 2 for classic queue has to be enabled:
```
classic_queue.default_version = 2
```

After restrat RabbitMQ server I enable Lazy policy: 
```
rabbitmqctl set_policy Lazy ".*" '{"queue-mode":"lazy"}' --apply-to queues
```

Run sender script to fill the queue,  sender.py: 
```
#!/usr/bin/env python3
import pika, sys, os

QUEUE_i = "dest-0-shard-0.i"
QUEUE_d = "dest-0-shard-0.d"

connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))

channel = connection.channel()

message = ' '.join(sys.argv[1:]) or "Hello World!"

channel.exchange_declare('retry', exchange_type='headers', durable=True)

channel.queue_declare(queue=QUEUE_i,
                      durable = True,
                      exclusive=False,
                      arguments={
                          'dest': 0,
                          'ip': 0,
                          'x-dead-letter-exchange': '',
                          'x-dead-letter-routing-key': 'global.l',
                      })
channel.queue_declare(queue=QUEUE_d,
                      durable = True,
		      exclusive=False,
                      arguments={
                          'dest': 0,
                          'ip': 0,
                          'x-dead-letter-exchange': '',
                          'x-dead-letter-routing-key': 'global.l',
                      })
channel.queue_bind(QUEUE_d, 'retry', routing_key='',  arguments={'dest': 0, 'ip': 0})

for i in range(55000):
    channel.basic_publish(exchange='',
                          routing_key=QUEUE_i,
                          body=message,
                          properties=pika.BasicProperties(
                              content_type='text/plain',
                              delivery_mode=pika.DeliveryMode.Persistent,
                              headers={"ip": 0, "dest": 0}
                          ),
                          mandatory=True,
                          )
    print(f" [x] Sent {i:05d} message: {message}")

channel.close()
```

And after finish it start reciever.py: 
```
#!/usr/bin/env python3
import pika, sys, os

QUEUE = "dest-0-shard-0.i"
counter = 0

def callback(ch, method, properties, body):
    global counter
    counter = counter + 1
    print(f" [x] {counter:05d}: {body.decode('utf-8') }")
    # print(" [x] %r" % (properties.headers,))
    ch.basic_ack(delivery_tag = method.delivery_tag)

    ch.basic_publish(exchange='',
                     routing_key='m-5.r',
                     body=body,
                     properties=pika.BasicProperties(
                         headers={"ip": 0, "dest": 0},
                         delivery_mode=pika.DeliveryMode.Persistent,
                     ),
    )
    print(" [x] Sent to retry %r" % (body,))


def main():
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
    channel = connection.channel()

    channel.queue_declare(queue=QUEUE,
                          durable = True,
                          arguments={
                              'dest': 0,
                              'ip': 0,
                              'x-dead-letter-exchange': '',
                              'x-dead-letter-routing-key': 'global.l',
                      })

    channel.queue_declare(queue='m-5.r',
                          durable = True,
                          arguments={
                              'x-dead-letter-exchange': 'retry',
                              'x-message-ttl': 300000,
                      })

    channel.basic_consume(QUEUE, callback)

    print(' [*] Waiting for messages. To exit press CTRL+C')
    channel.start_consuming()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Interrupted')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
```

 Queue "dest-0-shard-0.i" is crashed after few thousands of received+sent  messages
```
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>     supervisor: {<0.441.0>,rabbit_amqqueue_sup}
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>     errorContext: child_terminated
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>     reason: {{badmatch,{error,einval}},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>              [{rabbit_classic_queue_index_v2,reduce_fd_usage,2,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                   [{file,"rabbit_classic_queue_index_v2.erl"},{line,655}]},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>               {rabbit_classic_queue_index_v2,get_fd,2,
.....

2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>     offender: [{pid,<0.442.0>},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                {id,rabbit_amqqueue},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                {mfargs,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                    {rabbit_prequeue,start_link,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                        [{amqqueue,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             {resource,<<"/">>,queue,<<"dest-0-shard-0.i">>},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             true,false,none,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             [{<<"dest">>,signedint,0},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                              {<<"ip">>,signedint,0},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                              {<<"x-dead-letter-exchange">>,longstr,<<>>},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                              {<<"x-dead-letter-routing-key">>,longstr,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                               <<"global.l">>}],
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             <0.442.0>,[],[],[],undefined,undefined,[],
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             undefined,stopped,0,[],<<"/">>,
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             #{user => <<"guest">>},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                             rabbit_classic_queue,#{}},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                         recovery,<0.440.0>]}},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                {restart_type,intrinsic},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                {shutdown,600000},
2022-07-18 12:21:39.928840+02:00 [error] <0.441.0>                {child_type,worker}]
2022-07-18 12:21:39.930268+02:00 [error] <0.626.0> Restarting crashed queue 'dest-0-shard-0.i' in vhost '/'.
```

**Comment by michaelklishin** [comment] 2022-07-18 12:31
What version of RabbitMQ do you use?

If you mention an earlier discussion, consider linking to it.

**Comment by lhoguin** [comment] 2022-07-18 12:33
Hello, I will need to either reproduce this or figure out what's special in your environment that results in an error when attempting to close a file. It could be a problem with writing pending data to disk. A few questions:

- What OS/version are you using?
- The script doesn't seem to use confirms, is there a crash when confirms are used as well? With confirms I would expect the crash to occur with a potentially more useful error if this is a write error.
- Does v1 work in this environment?

**Comment by 3hedgehogs** [comment] 2022-07-18 13:11
I did test with RabbitMQ 3.10.5, 3.106 and inside Proxmox LXC container with Debian 11, inside VirtualBox Ubuntu Focal, inside kvm/qemu  VM with Debian 11, and see the same behaviors.

Classic queue v1 does not show such  problem.

**Comment by 3hedgehogs** [comment] 2022-07-18 13:20
If I put: ch.confirm_delivery()
to receiver.py in callback function before basic_publish  I see the same crash

**Comment by lhoguin** [comment] 2022-07-18 14:09
Thanks, I will try the scripts tomorrow.

**Comment by lhoguin** [comment] 2022-07-20 12:34
I have opened https://github.com/rabbitmq/rabbitmq-server/pull/5281 with a fix for this issue. Please try the patch if you can, it should apply cleanly to the 3.10.x branch as well.

And thanks a lot for the scripts! They made reproducing a blast. It was a tough one to figure out because reproducing was dependent on the consume rate, and the rate was going down if I tried to log too much. It was an obvious mistake in hindsight.

**Closed** 2022-07-20 17:36 UTC
