### ISSUE TITLE
Please publish amqp_client (AMQP 0-9-1) 4.0.x

### ISSUE THREAD

**Issue by ono** [rabbitmq/rabbitmq-server#11593] opened 2024-07-01 09:35 UTC
### Is your feature request related to a problem? Please describe.

amqp_client hasn't been updated since 3.12.14.

https://hex.pm/packages/amqp_client

### Describe the solution you'd like

Could you release 3.13.3 for the library, please?

rabbit_common seems to be up to date: https://hex.pm/packages/rabbit_common

**Comment by michaelklishin** [comment] 2024-07-01 17:43
We don't know we would be able to do that due to very significant infrastructure changes our team has to make on top of working on 4.x. We have to move release infrastructure that includes this client.

However, there are good news: you don't need Erlang AMQP 0-9-1 client 3.13.x to use it with RabbitMQ 3.13.x. In fact, the client hasn't changed in any meaningful way and it still supports RabbitMQ versions from 2.0 to 3.13 (obviously older versions can differ in behavior, e.g. `queue.delete` won't be idempotent with some really old ones).

**Comment by lucacorti** [comment] 2024-07-04 18:38
I'ts great to know 3.12.4 is compatible with rabbitmq server 3.13. The issue I'm facing with this is on the client side. `rabbit_common` 3.12.14, that `amqp_client` 3.12.14 depends on, does not build on OTP 27, so it prevents upgrading erlang for client applications depending on `amqp_client` 3.12.14.

**Comment by ono** [comment] 2024-07-04 22:16
@lucacorti I have shared a workaround [here](https://github.com/pma/amqp/issues/231) to compile with OTP 27.

Of course, it is not ideal and straightforward. Many users would get confused 😢  But I hope it helps.

**Comment by mkuratczyk** [comment] 2024-07-05 11:22
I'm not sure if that the problem or a part of the problem, but `v3.13.x` is now compatible with OTP27. It's still not supported to run RabbitMQ on OTP27 (or at least highly discouraged due to the performance regressions) but it can be compiled.

**Comment by mkuratczyk** [comment] 2024-07-10 09:05
We don't have a separate separate policy for the client but starting with the next version, 3.13.x should compile using OTP27 (since the PR I mentioned above was merged after 3.13.4 was released) and the client will most likely work just fine.

The regressions we see are mostly around Erlang processes that deal with large amounts of data (and therefore memory), especially in the range of 65-100B. I haven't tried to benchmark the client for such scenario, but even if prone to this issue, it'd probably require a sustained high throughput of such messages, so many client users wouldn't notice this anyway.

**Comment by michaelklishin** [comment] 2024-10-12 16:01
Superseded by https://github.com/rabbitmq/rabbitmq-server/issues/12510.

**Closed** 2024-10-28 19:55 UTC
Labels: enhancement

**Comment by michaelklishin** [comment] 2024-10-28 19:57
Both [`amqp_client`](https://hex.pm/packages/amqp_client) for AMQP 0-9-1 and [`amqp10_client`](https://hex.pm/packages/amqp_client) for AMQP 1.0 have had new releases published earlier today (`4.0.3`).

They can be used with RabbitMQ 3.13.x, in particular `amqp_client` (for AMQP 1.0, both `amqp10_client` 4.x and RabbitMQ server 4.x are highly recommended. Note that client can work with other AMQP 1.0 broker implementations)
