### ISSUE TITLE
rabbitmq-service.bat install failed on folder which has "(" or ")" in the name

### ISSUE THREAD

**Issue by LadaVarga** [rabbitmq/rabbitmq-server#1756] opened 2018-11-01 19:06 UTC
* RabbitMQ version: **3.7.8**
* Erlang version: **21.1**
* OS: **Windows**

**STR**
**When** Deploy RabbitMQ server to non-system drive with disabled 8do3 creation (Check: fsutil 8dot3name query e:)
**and** Folders has "(" or ")"
Examples: 
**8dot3name disabled + e:\program files (x64)\yourcomapnyname\123456789111\rabbitmq_server-3.7.8\sbin\**
**8dot3name enabled + c:\h(hj)\yourcomapnyname\123456789111\rabbitmq_server-3.7.8\sbin\ **
and Run "rabbitmq-service.bat install"
**Then** error thrown:
**\yourcomapnyname\123456789111\rabbitmq_server-3.7.8\plugins was unexpected at this time.**
![2018-11-01 20_02_20-window](https://user-images.githubusercontent.com/22859476/47873333-3df3d380-de11-11e8-9d6c-860bbb62009c.png)

During the investigation we figured out there is problem with these lines:
[https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-env.bat#L459-L468](url)
![2018-11-01 19_47_22-window](https://user-images.githubusercontent.com/22859476/47872842-f6b91300-de0f-11e8-9969-611bca6d8104.png)

**Solution**
Don't know.

**Workaround**
rem line or remove whole ascii check section (we don't have problem with previous version in that area at all and it is used by thousands of customers)
`call :filter_paths "%ERL_LIBS_orig%"`

**Comment by callofktulu** [comment] 2019-05-13 08:12
Greetings. Can you please confirm this issue is still happening with the latest version of rabbitmq-service.bat? Thank you!

**Comment by LadaVarga** [comment] 2019-05-13 10:06
Hello,
Was that fixed in the new releases? We still use workaround.

Workaround:
rem line or remove whole ascii check section (we don't have problem with previous version in that area at all and it is used by thousands of customers)
call :filter_paths "%ERL_LIBS_orig%"

**Comment by michaelklishin** [comment] 2019-05-13 10:57
Relevant PR pending QA: https://github.com/rabbitmq/rabbitmq-server/pull/1979. Note that anyone can give it a shot and share the findings.

**Comment by callofktulu** [comment] 2019-05-13 11:58
Hello @michaelklishin  #1979 pull request is not fixing this issue. I tried applying the changes of this pull request on rabbitmq-env.bat on a folder that has "(" and ")" characters and I still get "[foldername] was unexpected at this time." error.

**Comment by lukebakken** [comment] 2019-05-13 16:50
@callofktulu please attach your _complete, un-altered_ `rabbitmq-env-conf.bat` file.

@LadaVarga - it is very unlikely that we will support drives that have disabled 8.3 file names any time soon.

> Deploy RabbitMQ server to non-system drive with disabled 8do3 creation (Check: fsutil 8dot3name query e:)

**Comment by LadaVarga** [comment] 2019-05-13 17:03
@lukebakken Non-system drives has disabled 8dot3name by default in Windows. Many of our customers have "program files (x86)" in non-system drives.

**Comment by lukebakken** [comment] 2019-05-13 17:06
@LadaVarga a workaround is to use directories that don't contain problematic characters. The `.exe` installer supports the [`/D`](https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers%3F) argument to specify the installation directory.

**Comment by LadaVarga** [comment] 2019-05-13 17:33
@lukebakken as I wrote, we have the workaround. We will upgrade to newer version soon, we will see if we can fix it.

**Comment by strollo** [comment] 2019-05-16 14:57
The easiest way is to enable (as administrator) the 8dot3name support on **E:** with 
`fsutil 8dot3name set E: 0`

**Comment by strollo** [comment] 2019-05-16 16:04
Maybe the same trick of quote (for supporting extented path) and after unquote proposed in PR #1979 can be applied in this part of code like this...

Note: set ERL_LIBS="%~dpnx1" is the short form of %~dps1%~n1%~x1 and the s (short path form has been removed)

REM Ensure all paths in ERL_LIBS do not contains non-ASCII characters.
set ERL_LIBS_orig=%ERL_LIBS%
set ERL_LIBS=
REM 1) Use quotes to apply to full win paths
call :filter_paths "%ERL_LIBS_orig%"
REM 2) Remove quotes from converted path
CALL :unquote ERL_LIBS "%ERL_LIBS:"=%"
REM echo "After unquote ERL_LIBS: %ERL_LIBS%"
goto :filter_paths_done

:filter_paths
set paths=%1
set paths=%paths:"=%
for /f "tokens=1* delims=;" %%a in ("%paths%") do (
    if not "%%a" == "" call :filter_path "%%a"
    if not "%%b" == "" call :filter_paths "%%b"
)
set paths=
exit /b

:filter_path
REM Ensure ERL_LIBS begins with valid path
IF "%ERL_LIBS%"=="" (
    set ERL_LIBS="%~dpnx1"
) else (
    set ERL_LIBS="%ERL_LIBS%;%~dpnx1"
)
exit /b

**Comment by lukebakken** [comment] 2019-08-07 16:23
I will address this as part of #2068

**Comment by lukebakken** [comment] 2019-08-29 21:43
Fixed by #2068 and will ship in RabbitMQ `3.7.18`.

**Closed by lukebakken** 2019-08-29 21:43 UTC
Labels: bug, pkg-windows

**Comment by twjs76** [comment] 2020-06-05 09:14
This issue seems to appear again on 3.8.4, I was able to reproduce it with the standard isntaller. It looks like it was brought in through d3bd7d769be5bc50d029af4832c8b0121bd6b5bf

The following `if` in rabbitmq-env.bat seems to be problematic:
```
if defined ERL_LIBS (
    set ERL_LIBS=%RABBITMQ_HOME%\plugins;%ERL_LIBS%
) else (
    set ERL_LIBS=%RABBITMQ_HOME%\plugins
)
```
If `%RABBITMQ_HOME%` contains parenthesis, then the script will exit with the `... was unexpected at this time.` error

**Comment by michaelklishin** [comment] 2020-06-05 14:41
@twjs76 if you understand what the root cause is, please submit a PR. Thank you.

**Comment by lukebakken** [comment] 2020-06-08 17:40
@twjs76 thank you for your contribution.
