### ISSUE TITLE
RabbitMQ Stream Plugin & Connectivity Issues

### ISSUE THREAD

**Issue by nlm4145** [rabbitmq/rabbitmq-server#11314] opened 2024-05-24 12:57 UTC
### Describe the bug

Hello RabbitMQ community. I'm facing some connectivity issues with the stream plugin. Here's some context:

We have deployed up Rabbit MQ on a pod in our EKS Cluster but are finding difficulties maintaining between pod connectivity (between RabbitMQ and other applications) and maintaining port-forwarding capabilities from local machines.

If we want to let our other pods connect to RabbitMQ, the plugin configuration settings have to be:

```
  stream.advertised_host = rabbitmq-test.rabbitmq.svc.cluster.local # same as dnsConfig
  stream.advertised_port = 5552
```

But when port forwarding to the instance via:

` kubectl port-forward -n rabbitmq svc/rabbitmq-test 15672:15672 5672:5672 5552:5552`

And attempting to connect using a library, like rstream, we are not able to connect successfully.

we have to set the configs like this in order to connect locally via port-fowarding:

```
  stream.advertised_host = **localhost**
  stream.advertised_port = 5552
```

But then, our other pods are unable to connect to it, using localhost or rabbitmq-test.rabbitmq.svc.cluster.local.

Interacting with port 5672 works in either case but not 5552 (stream plugin).

How can we workaround this?

### Reproduction steps

1. deploy rabbitMQ on EKS with config settings:

```
  stream.advertised_host = rabbitmq-test.rabbitmq.svc.cluster.local
  stream.advertised_port = 5552
```

2. Port forward:
kubectl port-forward -n rabbitmq svc/rabbitmq-test 15672:15672 5672:5672 5552:5552
Use a library like rstream to connect using localhost or rabbitmq-test.rabbitmq.svc.cluster.local as hostname.

3. Redeploy but with these configs:
```
  stream.advertised_host = rabbitmq-test.rabbitmq.svc.cluster.local
  stream.advertised_port = 5552
```
4. Repeat step 2.

Int

### Expected behavior

We expect our other pods to be able to communicate with RabbitMQ cluster stream plugin, and be able to interact locally via port-forwarding.

**Comment by lukebakken** [comment] 2024-05-24 12:59
You already opened a discussion, there is no need for an issue because there is no evidence, as of yet, of a bug.

**Comment by lukebakken** [comment] 2024-05-24 12:59
Duplicate of https://github.com/rabbitmq/rabbitmq-server/discussions/11313

**Closed by lukebakken** 2024-05-24 12:59 UTC
Labels: bug
