### ISSUE TITLE
Address "Setting Ranch options together with socket options is deprecated" warning

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2069] opened 2019-08-06 15:48 UTC
Reported via [this `rabbitmq-users` message](https://groups.google.com/d/topic/rabbitmq-users/jsc1ajAjxZw/discussion).

[167735998]

**Comment by dcorbacho** [comment] 2019-08-09 08:42
This is fixed in `3.8`, see https://github.com/rabbitmq/rabbitmq-server/commit/9920cea9693d467c31838fed82fbb81adda7bf77

**Closed** 2019-08-09 08:42 UTC

**Comment by lukebakken** [comment] 2019-08-09 15:25
Thanks @dcorbacho !!!

**Comment by michaelklishin** [comment] 2019-08-12 09:33
Backported to `v3.7.x`.

**Comment by dingzhengkai** [comment] 2019-10-31 09:01
The warning log still  exists in rabbitmq 3.7.20, and i use [docker](https://hub.docker.com/_/rabbitmq) run rabbitmq, with default config file.

```erlang
[{running_applications,
    [{rabbitmq_management,"RabbitMQ Management Console","3.7.20"},
     {rabbitmq_management_agent,"RabbitMQ Management Agent","3.7.20"},
     {rabbitmq_web_mqtt,"RabbitMQ MQTT-over-WebSockets adapter","3.7.20"},
     {rabbitmq_mqtt,"RabbitMQ MQTT Adapter","3.7.20"},
     {amqp_client,"RabbitMQ AMQP Client","3.7.20"},
     {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.7.20"},
     {rabbit,"RabbitMQ","3.7.20"},
     {rabbit_common,
         "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
         "3.7.20"},
     {cowboy,"Small, fast, modern HTTP server.","2.6.1"},
     {ranch,"Socket acceptor pool for TCP protocols.","1.7.1"},
     {ssl,"Erlang/OTP SSL application","9.4"},
     {public_key,"Public key infrastructure","1.7"},
     {asn1,"The Erlang ASN1 compiler version 5.0.9","5.0.9"},
     {observer_cli,"Visualize Erlang Nodes On The Command Line","1.5.2"},
     {recon,"Diagnostic tools for production use","2.5.0"},
     {sysmon_handler,"Rate-limiting system_monitor event handler","1.1.0"},
     {os_mon,"CPO  CXC 138 46","2.5.1"},
     {cowlib,"Support library for manipulating Web protocols.","2.7.0"},
     {credentials_obfuscation,
         "Helper library that obfuscates sensitive values in process state",
         "1.1.0"},
     {crypto,"CRYPTO","4.6.1"},
     {mnesia,"MNESIA  CXC 138 12","4.16.1"},
     {tools,"DEVTOOLS  CXC 138 16","3.2.1"},
     {inets,"INETS  CXC 138 49","7.1.1"},
     {xmerl,"XML parser","1.3.22"},
     {jsx,"a streaming, evented json parsing toolkit","2.9.0"},
     {stdout_formatter,
         "Tools to format paragraphs, lists and tables as plain text",
         "0.2.2"},
     {lager,"Erlang logging framework","3.8.0"},
     {goldrush,"Erlang event stream processor","0.1.9"},
     {compiler,"ERTS  CXC 138 10","7.4.7"},
     {syntax_tools,"Syntax tools","2.2.1"},
     {sasl,"SASL  CXC 138 11","3.4.1"},
     {stdlib,"ERTS  CXC 138 10","3.10"},
     {kernel,"ERTS  CXC 138 10","6.5"}]},
{os,{unix,linux}},
{erlang_version,
    "Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64]\n"}
]
```

**Comment by michaelklishin** [comment] 2019-10-31 09:42
I cannot reproduce. The commit was backported to `v3.7.x` in https://github.com/rabbitmq/rabbitmq-server/commit/175dbfb69e9734748ef21098328b0f20de93fcca.

**Comment by dingzhengkai** [comment] 2019-10-31 09:54
@michaelklishin 

Sorry i did not clearly describe my case.

I used the following  Dockerfile to build my own image.
```Dockerfile
FROM rabbitmq:3.7.20-management

RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt

EXPOSE 1883 15675
```

then build

```
docker build -t demo/rabbitmq:3.7.20-management .
```

then run

```
docker run -d --name test demo/rabbitmq:3.7.20-management
```

and `docker logs test` show

```
2019-10-31 09:50:20.756 [info] <0.239.0> Running boot step pre_flight defined by app rabbit
2019-10-31 09:50:20.756 [info] <0.239.0> Running boot step notify_cluster defined by app rabbit
2019-10-31 09:50:20.756 [info] <0.239.0> Running boot step networking defined by app rabbit
2019-10-31 09:50:20.758 [info] <0.519.0> started TCP listener on [::]:5672
2019-10-31 09:50:20.758 [info] <0.239.0> Running boot step direct_client defined by app rabbit
2019-10-31 09:50:20.758 [info] <0.526.0> MQTT retained message store: rabbit_mqtt_retained_msg_store_dets
2019-10-31 09:50:20.759 [info] <0.544.0> started MQTT TCP listener on [::]:1883
2019-10-31 09:50:20.759 [warning] <0.547.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
2019-10-31 09:50:20.760 [info] <0.547.0> rabbit_web_mqtt: listening for HTTP connections on undefined:15675
2019-10-31 09:50:20.785 [info] <0.610.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2019-10-31 09:50:20.785 [info] <0.716.0> Statistics database started.
2019-10-31 09:50:20.785 [info] <0.715.0> Starting worker pool 'management_worker_pool' with 3 processes in it
2019-10-31 09:50:20.848 [info] <0.8.0> Server startup complete; 5 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * rabbitmq_web_mqtt
 * rabbitmq_mqtt
 completed with 5 plugins.

```

**Comment by michaelklishin** [comment] 2019-10-31 10:30
We need a way to reproduce without any custom Docker images or Docker in general. We have no idea what config file is used (`rabbitmq-diagnostics environment` will [print effective configuration](https://www.rabbitmq.com/configure.html#verify-configuration-effective-configuration).

This is mailing list material.

**Comment by michaelklishin** [comment] 2019-10-31 10:32
My only guess with this brief log snippet is that the warning is emitted for the MQTT listener, not the AMQP 0-9-1/AMQP 1.0 one. It must be confirmed (by disabling the plugin to compare) and a new issue opened in the MQTT plugin repository.

**Comment by dingzhengkai** [comment] 2019-10-31 10:45
You are very close to the truth, thanks.

In docker, when enable mqtt plugin, logs 
```
2019-10-31 10:40:33.771 [info] <0.413.0> started TCP listener on [::]:5672
2019-10-31 10:40:33.771 [info] <0.297.0> Running boot step direct_client defined by app rabbit
2019-10-31 10:40:33.771 [info] <0.420.0> MQTT retained message store: rabbit_mqtt_retained_msg_store_dets
2019-10-31 10:40:33.772 [info] <0.438.0> started MQTT TCP listener on [::]:1883
2019-10-31 10:40:33.796 [info] <0.487.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2019-10-31 10:40:33.796 [info] <0.593.0> Statistics database started.
2019-10-31 10:40:33.796 [info] <0.592.0> Starting worker pool 'management_worker_pool' with 3 processes in it
2019-10-31 10:40:33.862 [info] <0.8.0> Server startup complete; 4 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 * rabbitmq_mqtt
 completed with 4 plugins.
```

When enable `rabbitmq_web_mqtt` plugin, logs 
```
2019-10-31 10:40:33.862 [info] <0.8.0> Server startup complete; 4 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 * rabbitmq_mqtt
 completed with 4 plugins.

Unable to update config for app rabbitmq_management from a .conf file:  The app is already running.

Unable to update config for app rabbit from a .conf file:  The app is already running.
2019-10-31 10:41:12.181 [warning] <0.608.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
2019-10-31 10:41:12.182 [info] <0.608.0> rabbit_web_mqtt: listening for HTTP connections on undefined:15675
2019-10-31 10:41:12.182 [info] <0.604.0> Plugins changed; enabled [rabbitmq_web_mqtt]
````

**Comment by michaelklishin** [comment] 2019-10-31 11:04
I can reproduce if I enable `rabbitmq_web_stomp` and `rabbitmq_web_mqtt`.

**Comment by michaelklishin** [comment] 2019-10-31 11:05
You beat me to it. Thanks for confirming and filing the issue.

**Comment by RamKChalla** [comment] 2021-07-08 17:42
Not able to connect to RabbitMQ using java client - lib version 5.12.0, any recommendations

![image](https://user-images.githubusercontent.com/69894165/124967203-ff0e7680-dfd8-11eb-85ac-387c81b839fa.png)


Exception in thread "main" java.util.concurrent.TimeoutException
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:326)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1213)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1170)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1128)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1290)
	at gov.va.vamf.telehealth.rabbitmq.Send.main(Send.java:28)
2021-07-08 09:27:21,795 WARN  c.r.c.i.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Socket closed)

**Comment by michaelklishin** [comment] 2021-07-08 20:01
@RamKChalla there is a [dedicated doc guide](https://www.rabbitmq.com/troubleshooting-networking.html). A timeout likely means that TCP packets are dropped by an intermediary or the host that runs target RabbitMQ node. [Server logs[(https://www.rabbitmq.com/logging.html) can clarify whether the node observes any inbound connections that send **at least one byte of data**.

And please never ask questions on random two year old GitHub issues again. Mailing lists, Slack channels, forums, even GitHub discussions are all much better options.
