### ISSUE TITLE
Bug: Management UI not accessible if configured to use a path prefix

### ISSUE THREAD

**Issue by SteffenRossberg** [rabbitmq/rabbitmq-server#6017] opened 2022-10-04 18:56 UTC
### Steps to reproduce:
1. configure management UI to use a path prefix in ```rabbitmq.conf```, e.g. ```/rabbitmq```
```
management.path_prefix = /rabbitmq
```
2. try to access management UI using URI ```http://localhost:15672/rabbitmq/```

### Results
Access to the UI fails and shows only a blank page in browser. Login is not possible anymore.
If the management UI is behind a reverse proxy like NGINX and several services are routed on the same domain/ip/port using path prefixes instead of different sub domains or ports than it is possible that management UI accesses another service, which may or may not lead to exceptions in the browser console/log and/or service.

### Details
In line 6 of ```deps/rabbitmq_management/priv/www/js/oidc-oauth/helper.js``` function ```oauth_initialize_if_required()```  in main branch:
```
rabbit_base_uri = window.location.protocol + "//" + window.location.hostname + rabbit_port
```
an URI is build without path prefix, e.g. ```http://localhost:15672/``` and the UI uses this URI to access directly the management API in line 10, e.g. ```http://localhost:15672/api/auth``` instead of ```http://localhost:15672/rabbitmq/api/auth```:
```
request.open('GET', rabbit_base_uri + '/api/auth', false);
```
### Possible solution
A quick and dirty solution could be to add ```window.location.pathname``` to the URI too. But in my humble opinion it would be better to have the proper path prefix from the configuration accessible to add it to the URI. But this is far away from my poor web development skills...

### Version information
RabbitMQ: 3.11.0
Erlang: 25.1

**Comment by michaelklishin** [comment] 2022-10-04 20:15
Duplicate of #5984

**Closed by michaelklishin** 2022-10-04 20:15 UTC
