### ISSUE TITLE
New x-max-length-total and x-max-length-bytes-total queue arguments/policy definitions

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-server#2314] opened 2020-04-14 08:31 UTC
As far as I understand, one of the main goals of `overflow=reject-publish` mode is to prevent message loss. Instead of silently dropping messages from queue head, RabbitMQ will notify publisher and it will able to react accordingly.

Also,` overflow=reject-publish` mode has no meaning without some length limits, e.g. with `x-max-length` or `x-max-length-bytes` argument. But for those limits

> In all cases the number of ready messages is used; unacknowledged messages do not count towards the limit.

It make sense in default `overflow=drop-head` mode (rejected unacknowledged messages are dropped in case of overflow, but they're in danger of dropping anyway). But in `overflow=reject-publish` mode we usually don't want to lose **any messages**, including rejected unacknowledged. **That means, queue must be able to receive back all the rejected messages without dropping.**

That means, we need limit argument, which **do count unacknowledged messages toward the limit**.

@michaelklishin explained [here](https://github.com/rabbitmq/rabbitmq-server/issues/2313) why RabbitMQ can't and won't change the behavior of existing `x-max-length` or `x-max-length-bytes` arguments. He's definitely right, it shouldn't be implemented this way.

But what about **new**, non-breaking arguments? E. g. `x-max-length-total` and `x-max-length-bytes-total`.

**Comment by michaelklishin** [comment] 2020-04-14 09:30
In #2313 I also explained that there isn't enough evidence that this behavior is desired by a large enough percentage of the user base and that we want to focus on new queue types with fewer properties, not adding more and more to classic queues.

Sorry but the conclusion from #2313 does not change.

**Comment by michaelklishin** [comment] 2020-04-14 09:31
Effectively a duplicate of #2313.

**Closed by michaelklishin** 2020-04-14 09:30 UTC

**Comment by amills-vibeirl** [comment] 2024-01-20 21:50
help ~
https://stackoverflow.com/questions/77804007/when-using-x-max-length-and-x-overflow-how-to-send-to-dead-letter-exchange
