### ISSUE TITLE
Windows: RabbitMQ Service fails to start after Erlang upgrade from 20.x to 21.x 

### ISSUE THREAD

**Issue by TiagoJVO** [rabbitmq/rabbitmq-server#1969] opened 2019-04-01 15:09 UTC
RabbitMQ version: 3.7.7
Erlang version: 20.3
OS: Windows

I was updating Erlang version to 21.3, and when trying to re-install RabbitMQ service it fails to start.
I was able to find the problem [here](https://github.com/rabbitmq/rabbitmq-server/blob/2997bc4f072cf4755a2069bab5a0b246c726a70c/scripts/rabbitmq-service.bat#L59-L61).

The problem is that upgrading Erlang from 20.3 to 21.3, the installation folder that contains service binaries changes from `erts-9.3` to `erts-10.3`. Following the link mention above, you can see that to get the most recent version, the script is sorting the lines (with vertical sorting), meaning that in this case `9` is bigger that `1`. As consequence `erts-9.3` will be the last folder to be processed and the service will be created pointing to the old installation.

Steps to reprocuce:

1. Install Erlang 20.3
2. Install RabbitMQ 3.7.7
3. Install Erlang 21.3
4. Remove RabbitMQ service using `rabbitmq-service.bat remove`
5. Remove RabbitMQ service using `rabbitmq-service.bat install`
6. Start the service

**Comment by TiagoJVO** [comment] 2019-04-02 08:08
Is it possible to uninstall the older version by power-shell scripting? We have automated processes and a manual step is not an option. We also tried as workaround to defined `ERLANG_SERVICE_MANAGER_PATH` with the path to the correct folder. Looking at the script it seems that the environment variable is evaluated before being calculated. The problem is, if a process is already running before installing erlang, I can't set an environment variable on that process, and `rabbitmq-service.bat` will only check environment variables with "process" scope, not machine.

There are types of 3 errors on Event Viewer:
- `RabbitMQ: Erlang machine seems to die continously, not restarted.`
- `The RabbitMQ service terminated with the following error: The process terminated unexpectedly. `
- `RabbitMQ: Erlang machine stopped instantly (distribution name conflict?). The service is not restarted, ignoring OnFail option.`

Thanks in advance!

**Comment by lukebakken** [comment] 2019-09-17 21:59
Sorry for the delay, but I can't seem to reproduce this using my Windows 8.1 VM. When `rabbitmq-service.bat install` is run after installing Erlang 21.3, RabbitMQ starts fine. However, it is using the previous version of Erlang due to the sort order of the `Program Files\erl*` directories.

Assuming this is due to something in @TiagoJVO 's environment. Without more details, I'll close this issue.

**Comment by TiagoJVO** [comment] 2019-09-18 10:04
The problem starting RabbitMQ might be due to some SSL configuration (or other), but you just confirmed that it is using the wrong Erlang folder. The fact it starts its a matter of luck... Imagine when Erlang reaches version 19... RabbitMQ will still be using version 9... Don't you consider this a problematic Bug?

**Comment by michaelklishin** [comment] 2019-09-18 12:54
@TiagoJVO erts is already at version 10 in Erlang/OTP 22 and the majority of Windows users do not run into any issues. If multiple versions of Erlang are installed in a system, I guess it could be problematic but we see no evidence of this being a common scenario.

We would consider a pull request if you have a specific suggestion as to how the "correct" path has to be computed. Note that the definition of "correct" here is pretty subjective when multiple versions are installed side by side.

**Comment by lukebakken** [comment] 2019-09-18 15:46
> Erlang reaches version 19... RabbitMQ will still be using version 9... Don't you consider this a problematic Bug?

No. I will add a note to the Windows-specific documentation stating that old versions of Erlang should be removed when upgrading Erlang.

**Comment by TiagoJVO** [comment] 2019-09-18 16:18
That is a start yes... I'll try to get a fix for it and make a pull request

**Comment by lukebakken** [comment] 2019-10-08 18:42
@TiagoJVO - You can use this code to uninstall _all_ versions of Erlang via powershell:

https://github.com/pika/pika/blob/master/appveyor.yml#L74

```
Get-ChildItem -Path 'C:\Program Files\erl*\Uninstall.exe' | %{ Start-Process -Wait -NoNewWindow -FilePath $_ -ArgumentList '/S' }
```

Please note that the above requires an elevated, administrative powershell session.

**Comment by tastimur** [comment] 2020-02-07 08:02
> > Erlang reaches version 19... RabbitMQ will still be using version 9... Don't you consider this a problematic Bug?
> 
> No. I will add a note to the Windows-specific documentation stating that old versions of Erlang should be removed when upgrading Erlang.

I believe RabbitMQ take wrong version of Erlang from
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang
because of alphabetical sorting
If there is node 9.2 and 10.5 it gets 9,2
if I change "9.2" to "09,2" it gets 10.5 .

**Comment by michaelklishin** [comment] 2020-02-07 13:15
@tastimur if you have a set of steps to demonstrate this behavior, please file a new issue with more specifics. Thank you.

**Comment by tastimur** [comment] 2020-02-07 15:59
Initial Situation : Rabbit MQ 3.7.3 and Erlang Version 20.2

Environment Variable ERLANG_HOME has value C:\Program Files\erl9.2

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\9.2  has value C:\Program Files\erl9.2

-------------------
Rabbit MQ Stopped. 
Elang 20.3 has been installed.
Environment Variable ERLANG_HOME has still the value C:\Program Files\erl9.2
I changed it to  C:\Program Files\erl9.3

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\9.2  has value C:\Program Files\erl9.2
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\9.3  has value C:\Program Files\erl9.3


RabbitMQ has been installed 3.7.18
RabbitMQ service points now (You can find it in Windows Services) "C:\Program Files\erl9.3\erts-9.3\bin\erlsrv.exe"


-------------------
Rabbit MQ Stopped. 
Elang 21.0.1 has been installed.
Environment Variable ERLANG_HOME has still the value C:\Program Files\erl9.2
I changed it to  C:\Program Files\erl10.0.1

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\9.2  has value C:\Program Files\erl9.2
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\9.3  has value C:\Program Files\erl9.3
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\10.0.1  has value C:\Program Files\erl10.0.1


RabbitMQ has been installed 3.7.23

RabbitMQ service points still "C:\Program Files\erl9.3\erts-9.3\bin\erlsrv.exe"


Under the Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\ are 3 values.
10.01
9.3
9.2


I think RabbitMQ installation make an alphabetical sorting 
9.3
9.2
10.01
and choose the top of them.

**Comment by lukebakken** [comment] 2020-02-07 16:13
This is a known issue and it's due to how one of the `.bat` files lists the `C:\Program Files\erl*` directory to find Erlang.

**Comment by michaelklishin** [comment] 2020-02-07 16:14
OK. @lukebakken @dumbbell does this change in master then?

**Comment by lukebakken** [comment] 2020-02-07 16:14
No, it's still an issue as far as I know.

**Comment by tastimur** [comment] 2020-02-07 16:34
> This is a known issue and it's due to how one of the `.bat` files lists the `C:\Program Files\erl*` directory to find Erlang.

Nope.
It looks registry keys. I installed erlang also different folder.
If I manupilate the keys under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\ 
rabbitmq choose the right one.

**Comment by lukebakken** [comment] 2020-02-07 16:39
@tastimur OK, yes the `.exe` installer looks at the registry, and the `.bat` files look at the directory structure.

**Comment by michaelklishin** [comment] 2020-02-07 17:27
I suggest that we add more specifics to https://github.com/rabbitmq/rabbitmq-server-release/issues/117. @tastimur thank you for clarifying and doing this investigative work. It's most of the effort here.

**Comment by tastimur** [comment] 2020-02-07 17:51
Anytime. Thank you!.

**Comment by lukebakken** [comment] 2020-02-07 18:12
@michaelklishin fixing this issue also involves fixing the `.bat` scripts to sort correctly (if that's even possible), so I'll re-open this.

**Comment by dumbbell** [comment] 2020-02-10 10:42
In `rabbitmq-env.bat` in `master`, we already use a PowerShell oneliner to find `erl.exe`, because `where.exe` we used to use is unavailable in the newest Windows Server Amazon EC2 image we install to test the RabbitMQ installer.

We could expand that oneliner to do the sorting and backport it to `v3.8.x` and `v3.7.x`.

This doesn't solve the problem of the installer reading the registry however.

**Comment by lukebakken** [comment] 2020-03-18 19:01
It is not possible to change the behavior in NSIS. I have created the following documentation improvements to address this scenario: https://github.com/rabbitmq/rabbitmq-website/pull/953

[171866390]

**Closed by lukebakken** 2020-03-18 19:01 UTC
Labels: help-wanted, not-enough-information, pkg-windows, wontfix
