### ISSUE TITLE
Make it possible to add a 'description' column to connections etc

### ISSUE THREAD

**Issue by johnfoldager** [rabbitmq/rabbitmq-server#678] opened 2016-03-07 09:05 UTC
We would like to be able to programmatically add a description (or whatever it should be called) to at least each connection. Would probably also be usable for channels, exchanges, queues and bindings.

We have a service that listens for all connection events and we have the username at this stage. We can look up some relevant information about that user and then lookup the connection in RabbitMQ and would like to be able to add a description to that specific connection. This would be very useful for Operations and also for developers while debugging stuff.

In general we would programmatically put a description on at least connections and probably also channels and some of the queues created dynamically.
For bindings the description should be possible to set when you configure it. We would use this description to describe what that binding is used for etc.

**Comment by michaelklishin** [comment] 2016-03-07 09:59
Duplicate of #104.

**Closed by michaelklishin** 2016-03-07 09:59 UTC
Labels: duplicate

**Comment by johnfoldager** [comment] 2016-03-07 11:55
Can see the duplicate for #104 for connections, but what about the rest?

**Comment by michaelklishin** [comment] 2016-03-07 11:57
Channels don't have any metadata associated with them. I'm not sure if we can extend them without breaking things. Queues already have optional arguments you can use (RabbitMQ will simply ignore those it does not know). I believe all of them are displayed in the management UI.

**Comment by johnfoldager** [comment] 2016-03-07 13:03
Okay. Cool.... I wasn't aware that I could use arguments for something custom. Thanks
