### ISSUE TITLE
(FunctionClauseError) no function clause matching in RabbitMQ.CLI.Core.Memory.formatted_watermark/1

### ISSUE THREAD

**Issue by eLvErDe** [rabbitmq/rabbitmq-server#2964] opened 2021-04-10 06:53 UTC
Hello,

I think there is a bug in rabbitmqctl parsing of relative memory watermark:

```
/usr/lib/rabbitmq/bin/rabbitmqctl -q status
```

```
Stack trace: 

** (FunctionClauseError) no function clause matching in RabbitMQ.CLI.Core.Memory.formatted_watermark/1
    (rabbitmqctl 3.8.0-dev) lib/rabbitmq/cli/core/memory.ex:56: RabbitMQ.CLI.Core.Memory.formatted_watermark({:relative, 0.4})
    (rabbitmqctl 3.8.0-dev) lib/rabbitmq/cli/ctl/commands/status_command.ex:221: RabbitMQ.CLI.Ctl.Commands.StatusCommand.result_map/1
    (rabbitmqctl 3.8.0-dev) lib/rabbitmq/cli/ctl/commands/status_command.ex:68: RabbitMQ.CLI.Ctl.Commands.StatusCommand.output/2
    (rabbitmqctl 3.8.0-dev) lib/rabbitmqctl.ex:153: RabbitMQCtl.maybe_run_command/3
    (rabbitmqctl 3.8.0-dev) lib/rabbitmqctl.ex:121: anonymous fn/5 in RabbitMQCtl.do_exec_parsed_command/5
    (rabbitmqctl 3.8.0-dev) lib/rabbitmqctl.ex:584: RabbitMQCtl.maybe_with_distribution/3
    (rabbitmqctl 3.8.0-dev) lib/rabbitmqctl.ex:93: RabbitMQCtl.exec_command/2
    (rabbitmqctl 3.8.0-dev) lib/rabbitmqctl.ex:31: RabbitMQCtl.main/1
```

My config file is the following:

```
% This file managed by Puppet
% Template Path: rabbitmq/templates/rabbitmq.config
[
  {rabbit, [
    {loopback_users, [<<"guest">>]},
    {tcp_listen_options, [
         binary,
         {packet,        raw},
         {reuseaddr,     true},
         {backlog,       128},
         {nodelay,       true},
         {linger,        {true, 0}},
         {exit_on_close, false}
    ]},
    {cluster_partition_handling, ignore},
    {disk_free_limit, {absolute, 52428800}},
    {vm_memory_high_watermark, {relative, 0.4}},
    {default_user, <<"guest">>},
    {default_pass, <<"guest">>}
  ]},
  {kernel, [
    
  ]}
,
  {rabbitmq_management, [
    {listener, [
      {port, 15672}
    ]}
  ]}
].
% EOF
```

It used to work fine on branch 3.7.x but not 3.8.x, and I already looked at the GIT history and saw a lot of changes related to memory watermark parsing but I already have all of them.

Regards, Adam.

**Comment by michaelklishin** [comment] 2021-04-10 10:51
CLI tools do not parse the value, they format it. Last time this was brought up we could not reproduce.
The value is computed to an absolute one on node boot, so most likely if you move to `rabbitmq.conf` you won't be able to reproduce.

Thanks for sharing your config file.

**Comment by eLvErDe** [comment] 2021-04-10 10:53
As you may have notice the config file is generated, this is why I'm not moving to new format ;)

Do you think it can be fixed ? I think the same issue is occuring with disk minimum limit.

**Comment by michaelklishin** [comment] 2021-04-10 13:42
@eLvErDe the new format is drastically easier to generate, so you really should be moving to `rabbitmq.conf`. I don't know what can be done yet.

**Comment by michaelklishin** [comment] 2021-04-10 14:14
I have a PR ready but this config file has a value that was never supported:

``` erl
```

See this 3.6 era [`rabbitmq.config.example`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/docs/rabbitmq.config.example#L306-L320).

So even with one extra formatting clause, `status` would still trip up because free disk space limit is returned as `nil`.
My best guess is that on 3.7, this value silently disabled free disk space limit monitoring on the node but it did not affect
CLI tools output because, well, it was dumped as an Erlang term.

One nice thing about `rabbitmq.conf` is that it provides a reasonable amount validation for both keys and values.

**Closed** 2021-04-10 15:41 UTC

**Comment by eLvErDe** [comment] 2021-04-10 15:44
Thanks a lot, I'll ping debian to try to get this into debian 11 release too :)

**Comment by michaelklishin** [comment] 2021-04-10 15:58
@eLvErDe I'd not worry about that. Debian has its own release schedule and provided Erlang versions. After May 3rd we [will require Erlang 23.3 for future 3.8 releases](https://blog.rabbitmq.com/posts/2021/03/erlang-24-support-roadmap/) and that surely won't fly with them.

We provide our own apt repos and Erlang Debian packages, so simply [use those](https://www.rabbitmq.com/install-debian.html) instead.

**Comment by eLvErDe** [comment] 2021-04-10 16:01
Yes I know but I have many systems running RabbitMQ from debian and I'd like to avoid having to move to another source (yours or a patched RabbitMQ package).
My goal is to get this fix backported in RabbitMQ that will be shipped with incoming debian 11.
I'll try to work on that by the end of the day.

**Comment by eLvErDe** [comment] 2021-04-10 16:39
@michaelklishin 

I'm not sure the patch is fully working, I do see one weird thing:

Considering `{vm_memory_high_watermark, {relative, 0.8}},` config, rabbitmqctl status shows:
```
Memory high watermark setting: 0.8 of available memory, computed to: 26.8573 gb
```

Computed value is wrong, not matter what percentage I put it's always using 0.4 value, but it seems admin interface (on port 15672) is doing the same, are they both related ?

Regards, Adam.

**Comment by michaelklishin** [comment] 2021-04-10 18:21
@eLvErDe the patch addressed exactly what was reported here.

Both CLI tools and management plugin's stats database use  the same value reported by the memory monitor.

**Comment by eLvErDe** [comment] 2021-04-10 19:17
So it.means the engine is not using the value, weird I'm pretty sure it used to work but anyway, that's a different issue, thanks for the fix :)

**Comment by michaelklishin** [comment] 2021-04-11 05:43
@eLvErDe I cannot reproduce. Here are two examples:

``` ini
vm_memory_high_watermark.relative = 0.25
```

results in the following being reported:

```
Memory high watermark setting: 0.25 of available memory, computed to: 4.295 gb
```

another value:

``` ini
vm_memory_high_watermark.relative = 0.8
```

another output:

```
Memory high watermark setting: 0.8 of available memory, computed to: 13.7439 gb
```

Neither of the values reports the default 0.4 value.

Without any watermark settings I get

```
Memory high watermark setting: 0.4 of available memory, computed to: 6.8719 gb
```

**Comment by michaelklishin** [comment] 2021-04-11 05:51
If you take a close look at

``` erl
```

you'd notice that it has the same [incorrect value](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/docs/rabbitmq.config.example#L254-L264) as was pointed out earlier about the free disk space limit.
Therefore the node ignores it and uses the default.

I highly recommend using `rabbitmq.conf` instead of clinging to the good ole ways. The new format is drastically easier to generate and supports validation. And it only has been around since October 2017, so even the most conservative Debian users should approve.

**Comment by michaelklishin** [comment] 2021-04-11 05:58
``` erl
[
  {rabbit, [
    {vm_memory_high_watermark, 0.25}
  ]}
].
```

computes the value to `4.295 gb` on this machine, which is correct.

``` erl
[
  {rabbit, [
    {vm_memory_high_watermark, {relative, 0.25}}
  ]}
].
```

computes it to `6.8719 gb` which is actually about 40%.

So using an (undocumented) `{relative, N}` value is the only way to run into this.

**Comment by michaelklishin** [comment] 2021-04-11 07:38
#2966 makes it possible to set `rabbit.vm_memory_high_watermark` to a tuple of `{relative, N}` (in `advanced.config` format only). When the value set cannot be recognised, nodes will print a warning (not new in #2966) and fall back to the default value of `0.4` of computed runtime memory limit.
